### ISSUE TITLE
Sort CSV output on region and date

### ISSUE THREAD

**Issue by MalcolmShazell** [epimorphics/ukhpi#100]
It would be useful if the CSV download option would sort the output on region and date to allow easier processing of the data.

This should only be considered as part of the upcoming tranche of work and is not urgent

**Comment by MalcolmShazell** [comment]
Currently changing the dates results in dowloads in non-date order

**Comment by ijdickinson** [comment]
Have also endeavoured to ensure that the fix for #129 does not impact this requirement.

**Comment by MalcolmShazell** [comment]
@ijdickinson 
just tried a download for two regions and getting this

City of Plymouth 2017-01
United Kingdom 2017-01
City of Plymouth 2017-02

I was anticipating 
CoP 2017-01
CoP 2017-02
UK 2017-01

looks like you've sorted on date/region rather than region/date - or is this the best fix given the comments above on an upstream DSAPI bug?

**Comment by ijdickinson** [comment]
I sorted it that way because that makes more sense to me. Any way we can check with end-users what they would prefer? Maybe via the Linked-In group?

**Comment by MalcolmShazell** [comment]
yes - i'll arrange that

**Comment by MalcolmShazell** [comment]
@ijdickinson we've reached out to the linked in group - will update you when we have a reasonable number of replies

**Comment by ijdickinson** [comment]
@MalcolmShazell OK, but Lorna seemed to think that the main objective was to be consistent with the way that your other downloads are organised. Was that your reading too?

**Comment by MalcolmShazell** [comment]
@ijdickinson yes - i don't think we will resolve this before Tuesday - i would prefer not to have many code changes applied now until release. 
She will need to look at what the other downloads do and the feedback from the group before making a decision.

**Comment by MalcolmShazell** [comment]
working as Lorna intended
