### ISSUE TITLE
Selected statistics should appear on currently closed graphs when opened

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#104]
Steps to reproduce:

* from the browse page, select England as the location
* open house price index by buyer status
* select first-time-buyers, shows graph for FTB index
* open average price by buyer status
* graph is blank, should be visible and showing the line for first-time buyers

**Comment by ijdickinson** [comment]
@MalcolmShazell I think this has been obsoleted by other changes

**Comment by MalcolmShazell** [comment]
@ijdickinson confirm will close
