### ISSUE TITLE
New UKHPI: selecting a statistic on the graph - users should be able to click the box

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#106]
From user testing:

> Making selections on the words only (i.e. when choosing “All property types”, “Detached houses”) was counter-intuitive, as it is natural to click on the check boxes instead.

**Comment by ijdickinson** [comment]
Irritatingly, this works on my development machine but not when pushed to the dev server. Investigating.

**Comment by ijdickinson** [comment]
@MalcolmShazell This should be working on the dev server now.

**Comment by MalcolmShazell** [comment]
Confirm working correctly. 
One query - the boxes are hard to see now - should we be outlining them?

**Comment by MalcolmShazell** [comment]
confirm working
