### ISSUE TITLE
Entering a really vague term like ‘e’ or ‘and’ for example should bring up loads of results yet only 8 are returned (top 8????)

### ISSUE THREAD

**Issue by marklunn** [epimorphics/ukhpi#11]
Looks like it is sorted by first letter hits first sorted alphabetically followed by other results sorted alphabetically. No way to see there are more than the 8 displayed as could be situations where there are 8 exactly and wouldn’t know the difference.

**Comment by ijdickinson** [comment]
See comment on #10.

**Comment by marklunn** [comment]
Happy that the amendment to show 15 results is enough, however as you mention I think it would be good to have a label or something at the bottom that shows there are '15 +' results if there are more.

**Comment by MalcolmShazell** [comment]
We have had no issues raised around this since go live - happy the solution we have is working for the users.
