### ISSUE TITLE
New UKHPI: symbol for disambiguating lines is easily misinterpreted

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#112]
During the user tests, several people mistook the line-identification marker for a data-point, meaning that they tried to read the value from that point.

Proposed changes:

- don't make the marker line up with month ticks on the x-axis, so hopefully it's more obvious that it's not a value (i.e. the mouse-over stats won't display)
- change from randomly selecting a point to systematically positioning the markers near the y-axis
- (possibly) suppress the marker if the date range is less than two (?) months

**Comment by ijdickinson** [comment]
@MalcolmShazell Ready for QA

**Comment by MalcolmShazell** [comment]
confirm its working will ask product owners if this achieves the aims

**Comment by MalcolmShazell** [comment]
confirm product owner happy enhancement achieves desired goals
