### ISSUE TITLE
New UKHPI: improved location search

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#114]
In discussion with the project team last week, we noted that several users had difficulty with the current search facility. In particular, being required to select a *type of location* (country, county, etc) before being able to search was confusing. In part, we force the type-of-location search so that we can select the right map layer to highlight the result.

To respond to the users' difficulties we decided to: 

* remove the type-of-location selector from the search facility
* disconnect the map and text search facility, so that search results from more than one layer can be listed at once

**Comment by ijdickinson** [comment]
Improvements have been deployed

**Comment by MalcolmShazell** [comment]
looks good, any defects will be raised seperatly
