### ISSUE TITLE
New UKHPI: showing both the select location dialogue and the compare location dialogue not working

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#115]
Steps:

* click to show the 'select location' dialogue, choose a new location
* click to the 'compare with ...' tab on one of the content units
* click to 'select another location'

Expected: see the same dialogue both times.

Actual: on the second viewing of the location dialogue, the map is missing. Works the same if the sequence is reversed (i.e. show compare and then select)

**Comment by ijdickinson** [comment]
@MalcolmShazell Ready for QA

**Comment by MalcolmShazell** [comment]
confirm now working
