### ISSUE TITLE
UKHPI Map dissapears

### ISSUE THREAD

**Issue by MalcolmShazell** [epimorphics/ukhpi#116]
This is an odd one, If you leave the app page open for a time then come back to in - when you select compare with - the map doesn't display - refreshing the page will fix the issue but why does it happen in the first place?

I'm trying to narrow down the time frame for this effect.

Low priority to fix

**Comment by ijdickinson** [comment]
Is this different from #115?

**Comment by MalcolmShazell** [comment]
I'm not sure -  it may be a different way of getting to the same bug. 

When testing I selected change region a number of times and each time the map was there, then I had a conversation with Brian for a bit, came back and when trying to use change region the map wasn't displayed. The same happened after testing was interrupted a second time.

No other actions like compare were selected only change region - so it doesn't match the interactions you describe in 115. The key for this to happen was leaving the app open and not using it for some time

**Comment by ijdickinson** [comment]
OK, thanks Mal. If you can get a specific route to reproduce, that would be helpful!

**Comment by MalcolmShazell** [comment]
yes - its taking a bit of time to nail down the minimum time window for step 3 below. As it currently stands
1: open app in chrome
2: select a new region to view
3: leave app for 1 hour
4: map stops appearing.

**Comment by ijdickinson** [comment]
Do you interact with the page during the 1 hour, or leave it alone completely? (i.e. is that one hour sitting inert, or just one hour since refreshing the page)

**Comment by ijdickinson** [comment]
I couldn't reproduce this after leaving the tab containing the app dormant for two hours.

**Comment by MalcolmShazell** [comment]
I was away from the chrome tab doing other things i.e. email, investigating CSV files in notepad++ etc, then going back to the chrome tab

**Comment by MalcolmShazell** [comment]
Interesting - I cannot re-create this problem at home - I checked several times in work I could re-create it - will try again tomorrow.

**Comment by ijdickinson** [comment]
@MalcolmShazell Any luck with reproducing this? Or should we close for now as not-repeatable, and re-open if we can find a way to provoke it?

**Comment by MalcolmShazell** [comment]
can't re-create so look like the new map code has fixed this
