### ISSUE TITLE
IE11 - opening one graph in a theme opens all graphs in the theme

### ISSUE THREAD

**Issue by MalcolmShazell** [epimorphics/ukhpi#120]
If you select the initial graph in a theme that is hidden (click on the arrow to open the graph)- all the graphs in that theme become visible rather than the one selected

**Comment by ijdickinson** [comment]
@MalcolmShazell Deployed and ready to test

**Comment by marklunn** [comment]
Only graph selected is visible in theme upon clicking the arrow - happy to close
