### ISSUE TITLE
Sales volume by type of property in United Kingdom - graph not working

### ISSUE THREAD

**Issue by MalcolmShazell** [epimorphics/ukhpi#121]
Sales volume by type of property in United Kingdom shows an empty graph but switching to table view shows data.

**Comment by ijdickinson** [comment]
@MalcolmShazell Is this on IE? Because it seems to be working for me on Chrome (both the version currently on `dev-c` and the the version running on my dev server)

**Comment by MalcolmShazell** [comment]
no it was in chrome - at home - will check again when i get back as it wasn't working multiple times at home but does in the office <sigh>

**Comment by MalcolmShazell** [comment]
intermittant fault cannot re-created
