### ISSUE TITLE
IE11 select multiple locations - confirm dialogue greyed out 

### ISSUE THREAD

**Issue by MalcolmShazell** [epimorphics/ukhpi#122]
Not sure if this is related to 115 below (map goes missing)
compare two locations - all fine
add another location - map disapears as noted before
type in location i.e. devon and select it from list - confirm dialogue is greyed out.

this only happens in IE11 - all other browsers the confirm dialogue works

**Comment by ijdickinson** [comment]
@MalcolmShazell Do you have any suggestions for recreating this? I've just tried to follow the steps above using IE11/Win7, and it seemed to work for me. Specifically, I:

* started with the UK page
* added England as a compare for avg price, all property types
* added Scotland as a third comparison
* added NI as a fourth comparison

The confirm button ungreyed once I had selected a location, as normal. Just wondering if the steps you were following varied from mine in some way?

**Comment by MalcolmShazell** [comment]
We had some feedback from other users reporting this problem - for some on win8 it worked for others it didn't - it also doesn't work in win10 both with IE11 and Edge.

I'll add some screensots.

**Comment by ijdickinson** [comment]
@MalcolmShazell I can see that this is a thing that is happening, but I'm still not sure how to reproduce it. On my IE11, it works OK. Any clue as to what the difference might be that provokes this error?

**Comment by ijdickinson** [comment]
Fix deployed to dev-c

**Comment by MalcolmShazell** [comment]
confirm fixed
