### ISSUE TITLE
data in tables not displaying correctly

### ISSUE THREAD

**Issue by MalcolmShazell** [epimorphics/ukhpi#123]
The data when selecting table view does not display in order.
For the united kingdom
change dates to 01-jan-2015 to 01-dec-2016
select see data table
data diaplayed in the following order
oct
nov
dec
jan
feb
etc

**Comment by MalcolmShazell** [comment]
Update - when selecting another region after the first, the table reverts to the correct order. - the initial table display starts at nov 2016 - might the table sort not be refreshing the first time the dates are changed?

**Comment by ijdickinson** [comment]
Fix deployed.

**Comment by marklunn** [comment]
Data displayed in the correct order, happy to close.
