### ISSUE TITLE
Graphs with no data

### ISSUE THREAD

**Issue by MalcolmShazell** [epimorphics/ukhpi#125]
for example
Average price by buyer status in United Kingdom

currently we just have an empty graph - is there a better response we can provide for the user to indicate no data presennt?

**Comment by MalcolmShazell** [comment]
Annotate the graph with 'no data for these dates/region'

**Comment by ijdickinson** [comment]
Fix deployed.

**Comment by marklunn** [comment]
'Sorry, there is no buyer status data available for United Kingdom. Please select a different location.' is now visible on the graph in place of no data - happy to close
