### ISSUE TITLE
Region selector functionality: type name <enter> to select

### ISSUE THREAD

**Issue by MalcolmShazell** [epimorphics/ukhpi#127]
Currently if you enter the full name of the location i.e. england and press return you still need to select the correct value from the list.
If you type in a fully matching text string into the search box and hit <return> can the matching element be selected automatically.

**Comment by ijdickinson** [comment]
Fix deployed.

**Comment by marklunn** [comment]
Entering full name and pressing return selects the respective region and displays data so happy to close.
@ijdickinson just a thought i had - when you've typed part of a region, should you be able to scroll down by using the down arrow to highlight an option from the list?
