### ISSUE TITLE
NI all property values not displaying correctly

### ISSUE THREAD

**Issue by MalcolmShazell** [epimorphics/ukhpi#13]
If you make a selection for a NI local authority with any of the property subtypes selected the 'all property types' graph line isn't displayed until you deselect all the property subtypes.
The tables are returning data so I think this may be specifically a graph display issue.

**Comment by ijdickinson** [comment]
I've stopped it breaking (please confirm).

We should confirm if we're expecting to have e.g. `ukhpi:housePriceIndexDetached` for NI districts. It was those values being missing that was causing the breakage, and all I've done so far is harden the code against missing values.

**Comment by MalcolmShazell** [comment]
Yup working fine now sir.

Also confirm the sub data e.g. detached, semi, terrace and flat is not being provided for NI
