### ISSUE TITLE
Fix CSS issues on landing page

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#130]
In the development of the new UKHPI app, some changes are apparent to the CSS for the landing page. In particular, the row of logos of the contributing agencies is now a column. Also hyperlinks are underlined.

**Comment by ijdickinson** [comment]
Fixes deployed.

**Comment by MalcolmShazell** [comment]
Ian, I'm not sure what i'm supposed to be checking here - I can confirm
1: logos are in a row as expected
2: hyperlinks are underlined when hovering over them.
Is there anything else you have changed?

**Comment by ijdickinson** [comment]
@MalcolmShazell The only other check would be to compare with the current UKHPI landing page, in case there's anything I've missed.

**Comment by MalcolmShazell** [comment]
happy with this
