### ISSUE TITLE
Missing feature to download all data

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#131]
There's an action on the per-graph download sections to `download all the data`, and a link on the landing page as well. We don't currently have a destination for that action.

**Comment by ijdickinson** [comment]
The landing page link correctly goes to the HMLR gov.uk page. The download all link on the per-graph content units is now working (see #149)

**Comment by MalcolmShazell** [comment]
confirm links, will use 149 to validate downloaded data
