### ISSUE TITLE
Redirect /explore to /browse

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#132]
The old UKHPI application search page had the URL `/app/ukhpi/explore`. For convenience during development, the new app has been `/app/ukhpi/browse`. During the call with the product owner today, we discussed whether to leave it there or not. Conclusion was to leave it on `/browse`, and add a redirect from `/explore` to `/browse`, so that existing users who have bookmarked the URL will still be able to do so.

**Comment by ijdickinson** [comment]
Fix deployed.

**Comment by marklunn** [comment]
Hi @ijdickinson , am i looking at the correct region here?  As when i try to access http://lr-pres-dev-c.epimorphics.net/app/ukhpi/explore, then i'm taken to a Land Registry 'page not found' page as opposed to being redirected to http://lr-pres-dev-c.epimorphics.net/app/ukhpi/browse

**Comment by ijdickinson** [comment]
@marklunn Yeah, looks like it's not set up right. It's supposed to redirect to `/app/ukhpi/explore` but it's actually going to `/explore`, and so you're seeing the default 404 page

**Comment by ijdickinson** [comment]
Fix deployed to dev-c

**Comment by MalcolmShazell** [comment]
confirm this re-direct is now working correctly
