### ISSUE TITLE
Download per-graph data not respecting changed dates

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#133]
To reproduce:

* on the UKHPI browse page
* change the date range to Jan 2015 - Dec 2016
* see the graphs update
* go to the download tab
* click one of the download buttons

Expected: get a download of data for the selected date range
Actual: get a download of data for the default date range (year-to-date)

**Comment by ijdickinson** [comment]
Fix deployed.

**Comment by marklunn** [comment]
Have re-tested and correct data is showing for the dates.  Happy to close
