### ISSUE TITLE
Control to change the location of a graph is still too subtle

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#134]
During testing, @pshab didn't notice the control for changing the location from a graph

**Comment by ijdickinson** [comment]
I've made the button more obvious now.

**Comment by MalcolmShazell** [comment]
@ijdickinson - what am i checking here? - is the whitespace behind United Kingdom the change?

**Comment by ijdickinson** [comment]
Yes, the button is intended to look more like a button now, but without totally breaking the flow of the header

**Comment by MalcolmShazell** [comment]
confirm this is fine
