### ISSUE TITLE
Back button from compare page loses previous context

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#138]
When going 'back' from the compare locations page, you currently lose the selections you previously had (location, dates, etc)

**Comment by ijdickinson** [comment]
I have now deployed a fix for this to the dev server.

**Comment by MalcolmShazell** [comment]
@ijdickinson there is a difference in behaviour between browsers 
FF - when you hit the back button the non-default graphs you had open before moving to compare remain open, on edge and chrome when you go back there are closed.

Steps
change location to city of plymouth
change start date to jan 2015
open all graphs on page
click on compare location
click on the back button

I think the FF behaviour is the correct one - what were you expecting with this update?

**Comment by ijdickinson** [comment]
@MalcolmShazell Good observation. I think there's not much I can do about the open/closed graph state, because we dont' serialise that in the page URL. Firefox is being a bit clever to properly remember that.

The original problem was that going from, say, Plymouth to compare Plymouth vs. Portsmouth and then back would leave you on the UK page, not back on Plymouth. That's the behaviour I (hopefully) have fixed; the open/closed state of the graphs wasn't something I was expecting to preserve.

I agree it would be ideal if we could, but I don't think that's easily achievable. We could log a separate ticket about this on the 'future work' milestone?

**Comment by MalcolmShazell** [comment]
@ijdickinson - I'll have a word with Lorna to see if we should open another ticket for future work.
I'm happy this has fixed the original issue - i just wasn't sure if the difference in behaviour was an unintended defect or like you indicated a difference in the browsers default behaviour. 
With your confirmation I will now close this
