### ISSUE TITLE
Locations of graph markers sometimes is off the line

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#142]
For the markers on the graph, if the graph is very volatile the marker can sometimes 'float in space' rather than sitting directly on the line

**Comment by ijdickinson** [comment]
A good example is [Merseyside in 2015](http://lr-pres-dev-c.epimorphics.net/app/ukhpi/browse?from=2015-01-01&location=http%3A%2F%2Flandregistry.data.gov.uk%2Fid%2Fregion%2Fmerseyside&to=2018-01-01) and look at the percentage monthly change for Flats & Maisonettes

**Comment by ijdickinson** [comment]
Fix deployed on dev-c

**Comment by MalcolmShazell** [comment]
@ijdickinson i can't seem to re-create the issue which suggestes you've fixed the problem - can you remember what data you originally noticed the issue with?

**Comment by ijdickinson** [comment]
@MalcolmShazell There's a link in the comment above for Merseyside, which has lots of volatility and was quite obvious before the fix

**Comment by MalcolmShazell** [comment]
confirm looked at merseyside - then checked sheffield and liverpool - both are just as volitile and marker is on the line. Happy this is fixed
