### ISSUE TITLE
Change period more easily

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#143]
From @pshab, but it also came up during the user testing in Coventry: the only affordance to change the date range is back at the top of the page. It would be nice to have something on the graph itself.

**Comment by ijdickinson** [comment]
I've implemented a partial solution, sent requested comments from product ownership team as to whether we need to do more

**Comment by ijdickinson** [comment]
Lorna replied that she's happy to see how users get on with this fix

**Comment by MalcolmShazell** [comment]
confirm fixed
