### ISSUE TITLE
Highlight the currently active page in the nav menu

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#145]
Feedback from Dave Lockett

**Comment by ijdickinson** [comment]
Fix deployed to dev-c

**Comment by MalcolmShazell** [comment]
confirm this works.
n.b. it is only applied to the browse and compare pages as the SPARQL Query and Help pages take you away from the UKHPI app to standard land registry pages - these are created under different guidelines than the app which has multiple stakeholders advising the design
