### ISSUE TITLE
compare locations - sales volumes

### ISSUE THREAD

**Issue by MalcolmShazell** [epimorphics/ukhpi#148]
When you compare locations and select sales volumes is it possible to grey out those selection criteria that don't  have sales volumes avaliable e.g. detached houses

**Comment by ijdickinson** [comment]
Possible, but not easy. How much of a priority is this?

**Comment by ijdickinson** [comment]
@MalcolmShazell I have a proposed solution to this ticket, but it needs careful checking. As far as I can remember, the unavailable combinations are:

    { statistic: 'det', indicator: 'vol' },
    { statistic: 'sem', indicator: 'vol' },
    { statistic: 'ter', indicator: 'vol' },
    { statistic: 'fla', indicator: 'vol' },
    { statistic: 'ftb', indicator: 'vol' },
    { statistic: 'foo', indicator: 'vol' },

Have I missed any?

**Comment by ijdickinson** [comment]
@MalcolmShazell  Also, I noticed while testing that there are some weird values for sales volumes for some statistics. I presume this is just test data? (e.g. sales vol for new build has values for Jan 2018)

**Comment by ijdickinson** [comment]
@MalcolmShazell Actually, what I thought was test data is a display bug. See #158

**Comment by MalcolmShazell** [comment]
confirm working as intended
