### ISSUE TITLE
download all UKHPI data

### ISSUE THREAD

**Issue by MalcolmShazell** [epimorphics/ukhpi#149]
the download all UKHPI data button doesn't seem to contain all data - can't seem to attach a file - but I'd expect dowload all data to contail all 54 data elements

**Comment by ijdickinson** [comment]
Agreed, it seems to have suffered a regression. I'll investigate.

**Comment by ijdickinson** [comment]
Fix deployed to dev-c

**Comment by MalcolmShazell** [comment]
@ijdickinson the download all data file contains columns for 
sales volume detached
sales volume semi detached
sales volume terrace
sales volume flats
I think this is a defect as we don't carry values for those stats so will always be empty

**Comment by ijdickinson** [comment]
@MalcolmShazell OK, but I think that should be a separate ticket

**Comment by MalcolmShazell** [comment]
@ijdickinson roger that - will close and raise a new issue
