### ISSUE TITLE
Compare locations

### ISSUE THREAD

**Issue by MalcolmShazell** [epimorphics/ukhpi#150]
I think now we have 5 locations in the default view for compare locations we may need to provide a prompt to the user that the 'x' will remove a location.

Can we change the wording from
Compare UKHPI statistics across locations
to
Compare UKHPI statistics across upto five locations?

**Comment by ijdickinson** [comment]
Rather than change the title, I have added some explanatory text.

**Comment by MalcolmShazell** [comment]
confirmed with Lorna and Dave they are happy
