### ISSUE TITLE
Bring back the Shetland Isles!

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#151]
Request from RoS: can we change the size of the map element so that Shetland and Orkney Islands are visible by default?

**Comment by ijdickinson** [comment]
Not sure I can fully solve this. I have sent an email around to the product management team to discuss options.

**Comment by ijdickinson** [comment]
We have a proposed solution, but may not get time to implement it before we go live.

**Comment by ijdickinson** [comment]
> Probability Shetland Islands of one to one. We have normality. I repeat, we have normality. 
> Anything you still can't cope with is therefore your own problem.

Slightly misquoting Trillian, but the Shetland Islands should be visible on map open.

**Comment by MalcolmShazell** [comment]
confirm we have small almost unihabited islands back on the map
