### ISSUE TITLE
sales volume graph for all property types - not working 

### ISSUE THREAD

**Issue by MalcolmShazell** [epimorphics/ukhpi#152]
no sales volume graph for property type

**Comment by ijdickinson** [comment]
Hi Mal, can you give me some more details on this please? When I'm looking at lr-pres-dev-c, I can see the sales volume graph OK in Chrome and IE11

**Comment by MalcolmShazell** [comment]
humm - it was FF i noticed the problem in - but it is working in my home build - will check again when back in the office

**Comment by ijdickinson** [comment]
Working for me in Firefox 57on Linux

**Comment by MalcolmShazell** [comment]
yeah - thats what i'm running at home - I think my installation in work may be borked

**Comment by ijdickinson** [comment]
Also working for me in Firefox 57 on Windows

**Comment by ijdickinson** [comment]
> yeah - thats what i'm running at home - I think my installation in work may be borked
If it's still showing a problem when you get to the offfice, can you look on the JS console and see if there are any error messages please?

**Comment by MalcolmShazell** [comment]
will do sir
