### ISSUE TITLE
Change default period for initial view

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#157]
Currently, we show the last 12 months of data from the current month to the current month minus 12. This means that there is always a gap at the end of the graph, since the data always lags behind by at least one month.

If we can determine the publication day algorithmically, we can determine whether we're before or after publication day this month and adjust the default period to show the most recent data without needing to do a query every time.

@MalcolmShazell is checking whether there is a formula for determining the publication date in a given month.

**Comment by ijdickinson** [comment]
We discussed this at the call on 2018-01-12, and decided that we can't algorithmically determine the publication date, since they are declared by ONS each year. We will tweak the default display to go from current-month minus 13 to current-month minus 1 as a compromise.

**Comment by ijdickinson** [comment]
Fix applied

**Comment by MalcolmShazell** [comment]
confirm date now showing dec to dec as expected on landing
