### ISSUE TITLE
Incorrect dates on comparison rows for sales volumes with missing values

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#158]
See Sales Volume for New Build for four home nations plus UK. Dates run: Jan 2017, Feb 2017, Mar 2017, Apr 2017, Jan 2018, Jan 2018, Jan 2018, ...

**Comment by ijdickinson** [comment]
Fix deployed

**Comment by MalcolmShazell** [comment]
@ijdickinson is this in comparison view or any sales volumes for new build?

**Comment by ijdickinson** [comment]
@MalcolmShazell Specifiically in the comparison view, and it was important to include NI or UK in the comparison, because their sales volume figures lack behind the other geographies

**Comment by MalcolmShazell** [comment]
confirm fixed
