### ISSUE TITLE
Sales volume graph goes blank

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#162]
From @MalcolmShazell:

> spotted a flaw - sales volume by property type graph goes blank as soon as 
> you add another indicies e.g. detached houses on any of the other property type graphs

**Comment by ijdickinson** [comment]
Fix has been deployed to dev, staging, and, er, production! (but @MalcolmShazell and I did manually QA it first)

**Comment by MalcolmShazell** [comment]
confirm this is working now
