### ISSUE TITLE
App is generating larger log files than before

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#164]
Needs investigation

**Comment by ijdickinson** [comment]
There were two problems: the log-level had been left at `debug` following some earlier debugging on staging, and I also noticed there was a lot of noise from the rendering of partials. I have fixed both issues. Leaving the issue open for now until we confirm that log files are growing at an acceptably slow pace again.

**Comment by ijdickinson** [comment]
@bwmcbride I can't recall now - is this a concern that you raised originally? Are the logs an acceptable size now?

**Comment by bwmcbride** [comment]
@ijdickinson Yes it was.  Logs are now about 1MB per day compressed which is good.  Thanks for slimmin g them down.
