### ISSUE TITLE
JavaScript error with some versions of IE Edge

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#169]
Some versions of IE edge report an error:

    Object doesn't support property or method 'slice'

See: https://github.com/d3/d3-scale/issues/115

There is a workaround: https://github.com/Microsoft/ChakraCore/issues/1415#issuecomment-287888807

**Comment by MalcolmShazell** [comment]
any ideas how i would test this?

**Comment by ijdickinson** [comment]
@MalcolmShazell I don't think we can test it proactively. When we're running in production, I'd be expecting  the incidence of this error to reduce to zero. I was planning to leave the ticket open and check back in a week or so.

**Comment by ijdickinson** [comment]
Presume fixed
