### ISSUE TITLE
Not all graph lines showing up in zoom view

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#173]
To recreate: 

- go to the graph of average price by property type 
- check some additional property types (e.g detached and terraced)
- click on zoom view
- only 'all property types' line is shown

**Comment by MalcolmShazell** [comment]
confirm fixed

**Comment by MalcolmShazell** [comment]
closed the wrong one sorry.
@ijdickinson very odd behaviour in the zoom function. 
select additional data elements - click zoom - they are displayed
select another data element - click zoom - it isn't displayed

same effect with remove elements - remove them and they are still on the zoom graph 

I will show you tomorrow if necessary

**Comment by ijdickinson** [comment]
Fix deployed.

**Comment by MalcolmShazell** [comment]
confirm fixed
