### ISSUE TITLE
Print data tables - switching tabs

### ISSUE THREAD

**Issue by MalcolmShazell** [epimorphics/ukhpi#179]
If you select print data table a new tab opens up and focus shifts to the new tab.
go back to the old tab without closing the data table tab
select view another set of data
select print
view does not swap focus to the tab containing the data (although the data does update) user is just presented with the print dialogue box.

I think the focus should be going to the tab with the print table data.

**Comment by ijdickinson** [comment]
That's a browser behaviour, not something I can control. Imaginge the havoc if JavaScript could force the user to switch to another tab at will! What I do is set the `target` attribute of the `a` element to `_`, which is used by the browser as a trigger to control which content is in which tab. 

I would expect the normal behaviour would be for the user to close the print tab once they're done printing, in which case this won't be a problem.

**Comment by MalcolmShazell** [comment]
That's fine its not a defect if its a browser issue :)
