### ISSUE TITLE
Selecting a map region may report the name in Welsh

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#18]
Steps to reproduce:

* open the change selection dialogue
* select English counties
* click on Somerset on the map
* input element shows `Gwlad Yr Haf`

**Comment by ijdickinson** [comment]
Tagging @marklunn @lrmrthomas

**Comment by ijdickinson** [comment]
Fix deployed

**Comment by lrmrthomas** [comment]
Checked the incorrectly displaying local authorities and counties in the location field once selected on the map and all are now displaying correctly. Happy to close this issue.
