### ISSUE TITLE
cosmetic - view data in a table 

### ISSUE THREAD

**Issue by MalcolmShazell** [epimorphics/ukhpi#180]
If you select all property types and then data table,
semi detached houses and flats and masonettes have the 's' at the end appearing on the line below - is there enough room to give those two rows an extra character to prevent it happening?

**Comment by MalcolmShazell** [comment]
![image](https://user-images.githubusercontent.com/6670586/37352501-47d279e0-26d5-11e8-98c2-b5cf24217ca7.png)

Still getting the same problem sir

**Comment by ijdickinson** [comment]
@MalcolmShazell Looks like my fix doesn't work on IE. I'll try something else.

**Comment by ijdickinson** [comment]
@MalcolmShazell Please test again.

**Comment by MalcolmShazell** [comment]
@ijdickinson bug also appears on firefox 58,0,2, Also still in Edge - confim not an issue in Chrome

**Comment by MalcolmShazell** [comment]
confirm fixed in IE 11
