### ISSUE TITLE
print from compare view

### ISSUE THREAD

**Issue by MalcolmShazell** [epimorphics/ukhpi#182]
@ijdickinson when you print from the compare view the month/year is splitting across two lines in effect 'double spacing' each data row. It looks like there is room for it to appear on a single line - can you see if its a mistake or the table isn't wide enough with 5 elements so we will just have to put up with it.
n.b. it doesn't exhibit this behaviour on printing a data table on the browse screen

**Comment by ijdickinson** [comment]
Fix deployed.

**Comment by MalcolmShazell** [comment]
confirm fixed
