### ISSUE TITLE
Zoom graph fuctionality showing incorrect labels

### ISSUE THREAD

**Issue by MalcolmShazell** [epimorphics/ukhpi#194]
This is a bit of an oddball, I can't re-create the specific graph issue the origial user reported but can create the problem on a different graph.
1: select moray from the map
2: select each of the different property types 
3: goto average prive by buyer status and click the graph to enlarge - legend shows propety types rather than buyer status (see attached)
![image](https://user-images.githubusercontent.com/6670586/43316868-a42e0434-9192-11e8-824e-6a6a3f932389.png)

Avge price by funding status also appears to have the same problem
![image](https://user-images.githubusercontent.com/6670586/43316911-c94b2d8c-9192-11e8-86d0-b9a3b9957b61.png)

**Comment by ijdickinson** [comment]
I think a better refinement of the problem is:

* show a zoom graph
* close it
* show a different zoom graph
* the legend from the first graph is retained on the second graph

**Comment by MalcolmShazell** [comment]
confirm fixed
