### ISSUE TITLE
Cannot select King's Lynn and West Norfolk on map

### ISSUE THREAD

**Issue by lrmrthomas** [epimorphics/ukhpi#20]
King's Lynn and West Norfolk cannot be selected on the map. The area can be hovered over and caption is displayed but clicking on the area does nothing.

Can successfully select all other local authorities displayed on the map which loads the data for that location. 

King's Lynn and West Norfolk can be searched for using the location search field and area is highlighted on the map.

**Comment by ijdickinson** [comment]
Fix deployed

**Comment by marklunn** [comment]
Can now be selected, happy to close
