### ISSUE TITLE
Warn about new local authorities that are not yet in the ONS data

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#203]
As of April 2019, there are new local authorities in England that are not in the statistics from ONS, and won't be until the ONS master file is next updated (Feb 2020). In the meantime, we will issue a warning to users that search for the new authority names that the data will be forthcoming.

**Comment by ijdickinson** [comment]
@MalcolmShazell Can you please remind me a definitive list of the new LA's please?

**Comment by ijdickinson** [comment]
Requirements from the product owner:

From the 1 April the following structural changes to local government in England will take effect.

- A new Dorset Unitary Authority will be formed comprising the areas currently administered by East Dorset, North Dorset, Purbeck, West Dorset, Weymouth and Portland.
- The existing unitary authorities of Bournemouth and Poole and the non-metropolitan district of Christchurch will become Bournemouth, Christchurch and Poole Unitary Authority.-  The district of Forest Heath will merge with the borough of St Edmundsbury to become West Suffolk District Council.
- The districts of Suffolk Coastal and Waveney will merge to become East Suffolk District Council.
- The districts of West Somerset and Taunton Deane will be replaced by Somerset West and Taunton.

The changes affect around half a million titles which will have the following temporary entry added automatically:

> “From the 1 April 2019, this title is administered by ________”.

Programmes will be run over the coming months to remove this temporary entry and update the administrative area automatically.

**Comment by MalcolmShazell** [comment]
you can't actually search for Dorset Unitary Authority unless you cut and paste it into the search box or type dorsetu then add the spacebetween t and u. 
I don't think this is an issues as its a function of the search to block input once you've reached a selection of 1 in this case dorset - I will chack with dave lockett on monday to get his feedback

**Comment by MalcolmShazell** [comment]
East Suffolk District Council comes up in the selection list when typing east s - you do not get an option to select Dorset Unitary Authority when typing in dorset.
Bournemouth, Christchurch and Poole Unitary Authority does appear on selection list 
West Suffolk District Council does appear 
Somerset West and Taunton does not appear when typing somerset does appear when typing taunton

so there is some inconsistant behaviour in the search returning areas to be selected - any thoughts ian?

**Comment by ijdickinson** [comment]
@MalcolmShazell I did anticipate this problem. The approach we agreed was to consult the list of new LA's if the user's input did not match any of the existing location names. The problem with both `somerset` and `dorset` as inputs is that they **do** match existing locations, so the table of alternate names is not consulted.

If you carry on and type `somerset w`, the new UA should be suggested.

Options:

- we could not worry about the two edge cases
- change the algorithm so that we always consult the list of new names

The second option would be a fair bit more work. Personally, I favour option (i)! However, ultimately, it's you and Dave L who need to make the call.

**Comment by MalcolmShazell** [comment]
I'm with you on option 1 and will put it to dave on monday

**Comment by MalcolmShazell** [comment]
Somerset West and Taunton message shows Forest Heath, St Edmondsbury as previous LA
East Suffolk shows West somerset and taunton deane) as previous LA
West Suffolk shows Suffolk Coastal, Waveney as previous LA

**Comment by MalcolmShazell** [comment]
all now correct - happy for fix to be deployed
