### ISSUE TITLE
print this table 'orange background' too big

### ISSUE THREAD

**Issue by MalcolmShazell** [epimorphics/ukhpi#206]
![image](https://user-images.githubusercontent.com/6670586/62424189-602dc100-b6c3-11e9-90a1-1ef60919fd16.png)

with the new table display the backgrond box is too big (firefox)

**Comment by ijdickinson** [comment]
Here's the fixed version I'm about to commit:

![image](https://user-images.githubusercontent.com/63979/63090272-b10aa880-bf52-11e9-85bb-81c813417332.png)

**Comment by ijdickinson** [comment]
Here's the fixed version I'm about to commit (this time, showing the highlight!):

![image](https://user-images.githubusercontent.com/63979/63090328-d4355800-bf52-11e9-8557-c065d71e9ebb.png)
