### ISSUE TITLE
Sentry alert "converting circular structure in JSON"

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#207]
Following the deployment of version 1.2.1 to production, we have been seeing a cluster of error reports in Sentry, with variants on:

    Converting circular structure to JSON
    --> starting at object with constructor 'Vue'
    |     property '$options' -> object with constructor 'Object'
    |     property 'router' -> object with constructor 'VueRouter'
    --- property 'app' closes the circle

These alerts occur when the browser is Chrome or Edge, not Firefox. @MalcolmShazell reported that the app was not crashing, so the impact on the user experience is minimal. 

However, it seems worth investigating since we are likely to see a lot of Sentry traffic otherwise.

**Comment by ijdickinson** [comment]
@MalcolmShazell OK, I've updated the usual dev server if you want to check it out at your convenience.

**Comment by MalcolmShazell** [comment]
confirm fixed
