### ISSUE TITLE
500 response to OPTIONS requests

### ISSUE THREAD

**Issue by bwmcbride** [epimorphics/ukhpi#208]
We are seeing occurrences of 500 errors in the Apache logs on the production servers.

These are in response to an HTTP request "OPTIONS /app/ukhpi/assets/"

Would it be possible to respond with something other an 500 which looks like an internal server error?

Its not a big deal, but batches of "internal server errors" are a cause of concern when they show up in the monitoring.  Operator really should go and look at what is causing them.

**Comment by ijdickinson** [comment]
Thanks, will investigate. Can you provide a curl command that provokes the error?

Are PPD and Standard Reports also affected?

**Comment by bwmcbride** [comment]
curl -X OPTIONS http://lr-ppd-dev-pres.epimorphics.net/app/ukhpi/assets/

will reproduce the error

The equivalent requests for ppd and standard reports do not have the same problem - they return 404

curl -X OPTIONS http://lr-ppd-dev-pres.epimorphics.net/app/ppd/assets/
curl -X OPTIONS http://lr-ppd-dev-pres.epimorphics.net/app/standard-reports/assets/

**Comment by ijdickinson** [comment]
Migrated to https://github.com/epimorphics/hmlr-linked-data/issues/41
