### ISSUE TITLE
Layout bug in graph mouseover labels

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#21]
To reproduce:

* mouse over a graph near start of the x-axis. Label appears to the right of the y-axis line, and doesn't overlay any y-axis label text
* mouse all the way to the right-hand limit of the x-axis. Label shifts so that the rightmost edge is not off the graph
* mouse back to the start of the x-axis. Label is still shifted, and now overlays the y-axis line and label text

**Comment by ijdickinson** [comment]
Tagging @marklunn

**Comment by ijdickinson** [comment]
Fix deployed

**Comment by marklunn** [comment]
Label text now stays within the graph.  Happy to close
