### ISSUE TITLE
Version 1.2.2 does not work with IE11

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#210]
Reports from @MalcolmShazell  that users are experiencing non-functioning graphs when running UKHPI 1.2.2 on IE11

**Comment by MalcolmShazell** [comment]
@ijdickinson see 209 I don't think its just graphs not working, you can't select regions in the map - get a list of regions appear in the search bar, change dates etc

**Comment by ijdickinson** [comment]
Sorry, didn't spot that you had already created a ticket.

Closing as duplicate of #209
