### ISSUE TITLE
Placeholder UA names still present

### ISSUE THREAD

**Issue by MalcolmShazell** [epimorphics/ukhpi#222]
The places holders for the UA changes i.e.
Bournemouth, Christchurch and Poole Unitary Authority
along with the message 
We're sorry, but UKHPI statistics for Bournemouth, Christchurch and Poole Unitary Authority are not yet available. Statistics for this location will become available after the Office for National Statistics master regions table is updated in Feb 2020. Until then, the data will remain under the names of the previous local authorities: Bournemouth, Christchurch, Poole

We should remove these now we are supplying the new regious

**Comment by ijdickinson** [comment]
Thanks @MalcolmShazell. Can you remind me how we get these to show up please? I remember doing it, but the details are a bit hazy now :smile:

**Comment by MalcolmShazell** [comment]
hiya @ijdickinson - its in the map search - if you use the name search try bournmouth you will see both the placeholder and the new region

**Comment by ijdickinson** [comment]
@MalcolmShazell Are there any sites for which we should show a placeholder now? (i.e. any upcoming changes which are not in the data yet?)

**Comment by MalcolmShazell** [comment]
The only one i can see from the cov website is buckinghamshire - which is already a place (county) so i don't think we put in a place holder for the UA as that would just have been confusing.


Aylesbury Vale (E07000004), Chiltern (E07000005), South Bucks (E07000006), Wycombe (E07000007) = Buckinghamshire (E06000060), April 2020 (to be published on 17 June 2020)

So i think we just get rid of that bit of code

**Comment by ijdickinson** [comment]
@MalcolmShazell I've pushed an update to the dev server that should address this.

I've also updated the local authority polygons, some of which were looking a bit wonky at high zoom levels.

**Comment by ijdickinson** [comment]
Presuming fixed now
