### ISSUE TITLE
500 error instead of bad request

### ISSUE THREAD

**Issue by bwmcbride** [epimorphics/ukhpi#223]
There were a spike of 500 errors on LR around 01:10 on 06 Apr 2020.

These were caused by an attempted injection attack.  Since the responses were 500 errors, not bad requests, this suggests the attack got past initial parameter validation so it's not clear whether there might be a vulnerability.

In any case, bunches of 500 errors attract ops attention and consume time. 

The requests seemed to be injecting around the page number parameter, e.g:

GET /data/ukhpi.html?_page=0%20AND%20%28SELECT%201962%20FROM%28SELECT%20COUNT%28%2A%29%2CCONCAT%280x7171767871%2C%28SELECT%20%28ELT%281962%3D1962%2C1%29%29%29%2C0x7171787071%2CFLOOR%28RAND%280%29%2A2%29%29x%20FROM%20INFORMATION_SCHEMA.CHARACTER_SETS%20GROUP%20BY%20x%29a%29&min-percentageAnnualChangeDetached=16.94 

I've attached the log file.
[landregistry.dgu-access.log-20200406.gz](https://github.com/epimorphics/ukhpi/files/4442941/landregistry.dgu-access.log-20200406.gz)

**Comment by ijdickinson** [comment]
@bwmcbride `GET /data/ukhpi.html?...` is a call to Elda. We have a long standing issue that Elda tends to return 500 statuses when it should return 4xx responses. It seems to me we have two solutions:

- find some engineering time to do some maintenance on Elda
- replace Elda with SapiNT

Of those options, I'd personally favour replacing Elda with software that's being actively maintained. Either way, it's not a small job.

Were there any 500 responses from the Rails app that you want me to look at?

**Comment by bwmcbride** [comment]
Argh!  You are right.  I read it as a UKHPI app request - which is of course completely wrong.
