### ISSUE TITLE
Additional comms message to the UKHPI front page

### ISSUE THREAD

**Issue by MalcolmShazell** [epimorphics/ukhpi#224]
Given the data problems with the new Bournemouth Christchurch and Poole region - can the following be added to the front UKHPI page.

Note: Bournemouth, Christchurch and Poole data for 2018 to 2020 is missing from the February UK HPI report (published 22 April) due to data issues. The full dataset will be available in the March UK HPI report (published 20 May).

**Comment by ijdickinson** [comment]
@MalcolmShazell I added a date to the note, as I often find myself wanting to know that when I come across such warnings on the web. But I'm happy to take it out again if you prefer. Please have a look at: 

https://lr-dev.epimorphics.net/app/ukhpi

and let me know any changes you'd like me to make.

**Comment by MalcolmShazell** [comment]
looks fine to me - but I will check with Dave as he has final say

**Comment by MalcolmShazell** [comment]
got the nod from dave - happy to go with that ian

**Comment by MalcolmShazell** [comment]
thaks Ian much appreciated
