### ISSUE TITLE
bournmouth, christchurch and pool data is not showing up in the data table (only 2018)

### ISSUE THREAD

**Issue by MalcolmShazell** [epimorphics/ukhpi#228]
See note in slack

**Comment by ijdickinson** [comment]
Thanks Mal. Can you give a bit more detail please? What are you expecting to see, and what's actually happening?

**Comment by MalcolmShazell** [comment]
sorry ian, select bournmouth etc, - then set the time period to 2017 - 2020 and click on the display table - you will noitce it shows 2017 data no 2018 data then it continues with 2019-2020

**Comment by ijdickinson** [comment]
Hi Mal,
You asked us to put a notice on the web site for you:

![image](https://user-images.githubusercontent.com/63979/85374558-e1d14c00-b52c-11ea-829c-26117b168c14.png)

Is this the user reporting that problem, or is it different?

**Comment by ijdickinson** [comment]
Also, does that notice need to come down now (since we're past 20 May)?

**Comment by MalcolmShazell** [comment]
yes please
________________________________

**Comment by ijdickinson** [comment]
@MalcolmShazell If I go to the SPARQL query qonsole, and put in the following query:

```
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix ukhpi: <http://landregistry.data.gov.uk/def/ukhpi/>

SELECT DISTINCT
  ?place ?date ?ukhpi ?volume
WHERE
{
  values ?bcp {<http://landregistry.data.gov.uk/id/region/bournemouth-christchurch-and-poole>}

  ?bcp skos:prefLabel ?place.
  
  ?observation
    ukhpi:refRegion ?bcp;
    ukhpi:refMonth ?date;
    ukhpi:housePriceIndex ?ukhpi;
    ukhpi:salesVolume ?volume.
  
  FILTER (
  	?date >= "2017-01"^^xsd:gYearMonth
  )
}
  
ORDER BY ?date
```

it reveals that there is no 2018 data. So I'm afraid that the reason that the UKHPI app is not showing the data in the table is that it's not present in the store.

**Comment by ijdickinson** [comment]
I think we can close this now. Please re-open if more investigation is needed
