### ISSUE TITLE
Keyboard focus: dialogue box for location picker under HP statistics

### ISSUE THREAD

**Issue by lizscuffell** [epimorphics/ukhpi#249]
The tabs above the map never receive keyboard focus i.e. Local Authorities, Regions of England, Counties of England

**Comment by ijdickinson** [comment]
@lizscuffell  Once the tabgroup has the focus, you can use the arrow keys to move between the different tabs. I *think* this is standard behaviour (but honestly I'm not 100% sure)

**Comment by lizscuffell** [comment]
Happy to close as this is standard behaviour.
