### ISSUE TITLE
Download data link colour contrast

### ISSUE THREAD

**Issue by lizscuffell** [epimorphics/ukhpi#259]
Under the download data tab, the buttons indicating download actions are green with a white link. When focus is on them, this link colour turns to navy blue which is too close to the green
![image](https://user-images.githubusercontent.com/37189169/93854749-34e2a880-fcae-11ea-89a2-8e6cf57db2a2.png)

**Comment by ijdickinson** [comment]
@lizscuffell Colour has been updated

**Comment by lizscuffell** [comment]
Colours altered and contrast ratio fixed. Closing issue
