### ISSUE TITLE
Link to download all data

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#26]
The UKHPI landing page includes a link for users to download all of the data. The target for that link is not set.

**Comment by ijdickinson** [comment]
I've added the link that @MalcolmShazell gave me. It 404s at the moment, but it won't ... we hope! ... on Tuesday

**Comment by marklunn** [comment]
Link to download the data is on the landing page, but I'm currently getting 404 error - page not found

**Comment by ijdickinson** [comment]
@marklunn Yes, see my comment above. It's expected to 404 at the moment, since the data hasn't yet been released.

**Comment by ijdickinson** [comment]
@marklunn @MalcolmShazell Link seems to be (a) working and (b) relevant :) I think we can close this now

**Comment by marklunn** [comment]
@ijdickinson the link to view the UK House Price Index Reports for April 2016 works fine, but the link to download the data as CSV files doesn't seem to be working, I get a 'page not found' error.  Is this expected at the moment?

**Comment by ijdickinson** [comment]
@marklunn That's the LR gov.uk site, I have no control over what happens there. You'll need to report that issue to Stephanie Hill.

**Comment by marklunn** [comment]
@ijdickinson Ah ok no worries, i'll pass that on and close this one now.

**Comment by marklunn** [comment]
Also checked the link again and it seems to be working now!
