### ISSUE TITLE
Container Handover Feedback

### ISSUE THREAD

**Issue by mika018** [epimorphics/ukhpi#311]
The repo should have [github-workflows](https://github.com/epimorphics/github-workflows) enabled. See the link to find out how to set it up. But a checklist might also help:
- [ ] include the `hmlr` subrepo
- [ ] add a `deployment.yaml` file to map branches/tags to the deployed environments
- [ ] make sure that the `Makefile` has the [three required targets](https://github.com/epimorphics/github-workflows#makefile). 

Apart from that make sure that the `Dockerfile`:
- [ ] uses a multi-stage build 
- [ ] doesn't use ARGS for anything apart from parameterising the base image but rather uses ENVS.

Find more details in the [Containers Current Practice](https://github.com/epimorphics/internal/wiki/Containers---Current-Practice) document.

**Comment by tomguilbert** [comment]
@mika018 - is this still relevant or post LR lift and shift is it all redundant now?

**Comment by mika018** [comment]
It is redundant, safe to close
