### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#32]
Need a consistently referenced favicon

**Comment by marklunn** [comment]
In Internet Explorer the favicon is bigger than in Chrome and Firefox causing the text to not be on the same line
![favicon](https://cloud.githubusercontent.com/assets/13219344/16491302/59c6a80e-3ed5-11e6-8cd9-aaf2c1aaf04e.PNG)

**Comment by ijdickinson** [comment]
@MalcolmShazell @marklunn Ping to QA and close if appropriate please

**Comment by ijdickinson** [comment]
Actually, I think I need a clarification on this. The favicon is the small icon that shows up on the tab bar in desktop browsers, or can be used as a launch icon on the home screen in iOS and Android. It sounds like the Internet Explorer issue is about the home icon on the main page layout, which is a different issue.

**Comment by marklunn** [comment]
@ijdickinson Yes you are correct there, shall I raise a separate issue for the home icon on IE?

**Comment by ijdickinson** [comment]
@marklunn Yes please, and then I think we can close this one.

**Comment by marklunn** [comment]
Happy to close - new issue raised for IE home icon
