### ISSUE TITLE
Percentage change graph

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#33]
On the percentage change graph, it might be clearer if the x-axis line was at y=0, rather than at the foot of the graph. The x-axis labels would remain at the foot of the graph.

**Comment by ijdickinson** [comment]
After discussing with Mal yesterday, we decided the appropriate change was to add an additional axis line at `y = 0`, to indicate to users that there are two halves of the graph.

**Comment by marklunn** [comment]
Additional axis line at y = 0 is visible on percentage change graphs. Happy to close
