### ISSUE TITLE
Change 'temporary icon'

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#34]
The image file for the UKHPI icon is called `temporary-icon`. Since we decided to keep it, it's no longer temporary!

**Comment by MalcolmShazell** [comment]
Ian,

Is this where you right click on the icon and investigate the element and see its now calleed UKHPI-icon?

**Comment by ijdickinson** [comment]
Yes. It doesn't really need QA I suppose, but we have the pattern that I should not close the issues that I open!

**Comment by MalcolmShazell** [comment]
That's fine sir - I just wanted to make sure I had eyeballed the change correctly :)
