### ISSUE TITLE
Welsh translations of landing pages

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#38]
The old Welsh translation is obsolete as the copy has changed. Once the new pages are stable, we can request new Welsh translations, and put back the `Cymraeg` link buttons

**Comment by ijdickinson** [comment]
Adding Liz, as someone will have to task the translation team with the job of doing the translation. I'm happy to do whatever is needed to support the translators.

**Comment by ijdickinson** [comment]
Is this in scope for the 2017 project?

**Comment by MalcolmShazell** [comment]
checking with Lorna - will close and add to the user stories if relevant to the 2017 work
