### ISSUE TITLE
'Change selection' not clear 

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#39]
Beta-test feedback:

> I didn’t realise the change selection was my tool to view my request 
> (Could be called something more obvious?)  
> Once in the change selection remainder of request was straightforward

**Comment by ijdickinson** [comment]
Review wording with Liz

**Comment by ijdickinson** [comment]
Fix deployed

**Comment by marklunn** [comment]
customise your search button in place, happy to close
