### ISSUE TITLE
Map selection not reflected on radio button

### ISSUE THREAD

**Issue by marklunn** [epimorphics/ukhpi#4]
When selecting a country from clicking on the map, the radio button selected on the list of countries does not change to reflect this.

**Comment by ijdickinson** [comment]
Hi Mark,
Can you give some more details of steps to reproduce, browser version, etc. The demo was working when I gave it in Croydon, so I need to work out what's different from what you are seeing. Thanks

**Comment by marklunn** [comment]
Hi Ian,
I'm using the latest version of Firefox, which I think is 46.0.1.

If I select Wales then Scotland it is fine, but when I then select Wales again the radio button stays on Scotland.  Also if I select England, Scotland and then Wales it is fine but then I select England the radio button stays on Wales.  So not sure if it's something along the lines of it works properly the first time a country is selected but if a country is selected again the radio button doesn't change?

**Comment by ijdickinson** [comment]
OK, thanks. Is there anything on the JavaScript console after it starts to go wrong?

**Comment by marklunn** [comment]
Here is the output on the console when it goes wrong:

onPreferencesChange  application-15be2c6411eee7f6856d81cdf5f6f9706750a71b3e1c0a7b68007b2a5f65b062.js:212:29121

onPreferencesChange  application-15be2c6411eee7f6856d81cdf5f6f9706750a71b3e1c0a7b68007b2a5f65b062.js:212:29121

missing value for ukhpi:percentageChange 2014-12 application-15be2c6411eee7f6856d81cdf5f6f9706750a71b3e1c0a7b68007b2a5f65b062.js:212:32187

onPreferencesChange  application-15be2c6411eee7f6856d81cdf5f6f9706750a71b3e1c0a7b68007b2a5f65b062.js:212:29121

onPreferencesChange  application-15be2c6411eee7f6856d81cdf5f6f9706750a71b3e1c0a7b68007b2a5f65b062.js:212:29121

missing value for ukhpi:percentageChange 2014-12 application-15be2c6411eee7f6856d81cdf5f6f9706750a71b3e1c0a7b68007b2a5f65b062.js:212:32187

**Comment by ijdickinson** [comment]
Hmm, that's just normal log junk (which I should remove). OK, I'll dig in and see what's going on. Thanks

**Comment by ijdickinson** [comment]
I've pushed a new version with hopefully a fix. The map performance on Firefox does seem sluggish compared to Chrome though. I'll need to look at that.

**Comment by marklunn** [comment]
re-tested and passed. Happy to close ticket
