### ISSUE TITLE
Beta test feedback: downloading to spreadsheet

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#40]
A beta-tester

> 2) Download in a spreadsheet – Perth and Kinross averages prices 
> for detached houses and the monthly percentage change for 2014

> Would have expected to request the monthly percentage change 
> by year and had to export into a spreadsheet for all the dates 
> and then filter by year?

ijd: I'm not sure I can interpret this.

**Comment by ijdickinson** [comment]
@MalcolmShazell to get some feedback from the user

**Comment by MalcolmShazell** [comment]
killing this - we have had no other complaints about the spreadsheet download
