### ISSUE TITLE
UKHPI - 1.3.1: Info and Relationships

### ISSUE THREAD

**Issue by bogdanadrianmarc** [epimorphics/ukhpi#405]
See https://docs.google.com/spreadsheets/d/1YS3N5ps9pJGFOxBDi9C2DwA37WQPIVax/edit?gid=1215429860#gid=1215429860&range=6:6

**Comment by bogdanadrianmarc** [comment]
@tomguilbert The requirement for this ticket is to provide a summary of the information displayed on the graph. However, this is already achieved by the data table in an accessible manner, as shown here:
![Image](https://github.com/user-attachments/assets/3cc7b320-93ef-4ac1-a2ee-40fdf428c5cf)

I propose to close this as completed, unless there is something else to be addressed.

**Comment by tomguilbert** [comment]
@bogdanadrianmarc - could there be a pointer for screen reader users from the graph to the table, so they understand that they can get a more accessible version fo the information there?

**Comment by bogdanadrianmarc** [comment]
> @bogdanadrianmarc - could there be a pointer for screen reader users from the graph to the table, so they understand that they can get a more accessible version fo the information there?

Sure thing! I'll look into adding something that's hidden to the normal user, but available for screen readers 👍

**Comment by bogdanadrianmarc** [comment]
@tomguilbert I created a new PR [here](https://github.com/epimorphics/ukhpi/pull/427) with the changes, let me know if these look good to you, added before and after screenshots as well

**Comment by tomguilbert** [comment]
@bogdanadrianmarc - I think I understand what you're trying to do here, but I think you will get tied up with other issues around logical ordering of the tabs. What I meant by my comment was could you add something to the graph description that explains that the data underlying the graph is available in more accessible form via the data tab?

**Comment by DanielCouzens** [comment]
I have asked Gemma for some clarification on this ticket. I have been unable to find a way to add a description directly to the tabs. However, I can add a description to the tab panel and advise the user who is using a screen reader on the best way to use the tabs for accessibility.

**Comment by gemma-marriage** [comment]
@DanielCouzens I agree adding a desciption to the tab panel (assuming just in the code) would solve it - that's probably best, otherwise a code snippet to the whole graph here to explain that the accessible data for the graph can be found under the 'See data table' tab a bit like this example - 

![image](https://github.com/user-attachments/assets/827d9bc0-786c-4f21-9911-521c5753fa84)

The issue at the moment is that it's not clear that is where they can go for data in a more accessible format, so I wonder if also changing the tabs to say 'See data - graph / See data - table' or using a colon instead of a dash, may be a little clearer to all users what is beneath, but that's up to you.

**Comment by DanielCouzens** [comment]
This is in review. Pr https://github.com/epimorphics/ukhpi/pull/433

**Comment by DanielCouzens** [comment]
This is has been merged into dev and is ready to check @tomguilbert

**Comment by tomguilbert** [comment]
Thanks @DanielCouzens - not sure how to test this - can you give me a demo or a screenshot please?

**Comment by DanielCouzens** [comment]
![Screenshot from 2024-09-02 09-25-45](https://github.com/user-attachments/assets/44c9a375-571f-4a6b-849d-d2127133f525)

@tomguilbert if the above screenshot isn't clear, I can do a demo whenever you are free...

**Comment by DanielCouzens** [comment]
@tomguilbert there are translations to Welsh in other areas of the App where text is specific to screenreaders! So we do need a translation for my paragraph...

**Comment by tomguilbert** [comment]
OK - this looks good for the English text so I would say we call this done but create a new ticket for the welsh translations. Could you do that and insert the English copy you want to be translated please? If you assign it to me I'll get the translation done alongside the accessibility statement.
