### ISSUE TITLE
UKHPI - 1.4.3 Contrast (Minimum)

### ISSUE THREAD

**Issue by bogdanadrianmarc** [epimorphics/ukhpi#407]
See https://docs.google.com/spreadsheets/d/1YS3N5ps9pJGFOxBDi9C2DwA37WQPIVax/edit?gid=1215429860#gid=1215429860&range=9:9

**Comment by bogdanadrianmarc** [comment]
Completed as part of https://github.com/epimorphics/ukhpi/issues/406

**Comment by tomguilbert** [comment]
@bogdanadrianmarc I'm going to need some screenshots/guidance on what you have done here so I can tell if you have met the requirement. Also, I think from the wording on the PRs as if you are addressing the issues in rows 10 and 11 of the spreadsheet (but the link above is to row 9)?

**Comment by bogdanadrianmarc** [comment]
> @bogdanadrianmarc I'm going to need some screenshots/guidance on what you have done here so I can tell if you have met the requirement. Also, I think from the wording on the PRs as if you are addressing the issues in rows 10 and 11 of the spreadsheet (but the link above is to row 9)?

The link points to row 9 as that is the main issue, but rows 10 and 11 are sub-issues of the main one so I've addressed them as well in this ticket. These are screenshots from before:
<img width="754" alt="Screenshot 2024-08-20 at 16 03 01" src="https://github.com/user-attachments/assets/1d5c06e5-39af-4d88-8008-feb1e2e7c948">
<img width="1025" alt="Screenshot 2024-08-20 at 16 03 27" src="https://github.com/user-attachments/assets/96974628-bbd9-46c2-8729-5fc5a6d0a321">

and after:
<img width="540" alt="Screenshot 2024-08-20 at 16 03 06" src="https://github.com/user-attachments/assets/6dda5b09-8146-4bb0-b104-a9307f03a9d5">
<img width="977" alt="Screenshot 2024-08-20 at 16 03 19" src="https://github.com/user-attachments/assets/7292cce3-8548-4e30-a749-203704d3ca39">

Notice the links are all underlined for better visibility. Modal close button also has a bigger focusable area so it can be clicked easier, and the location error message is now more visible as well.

**Comment by tomguilbert** [comment]
OK great thanks @bogdanadrianmarc
