### ISSUE TITLE
UKHPI - 1.4.11: Non-text Contrast

### ISSUE THREAD

**Issue by bogdanadrianmarc** [epimorphics/ukhpi#408]
See https://docs.google.com/spreadsheets/d/1YS3N5ps9pJGFOxBDi9C2DwA37WQPIVax/edit?gid=1215429860#gid=1215429860&range=12:12

**Comment by tomguilbert** [comment]
@bogdanadrianmarc I'm going to need some screenshots/guidance on what you have done here so I can tell if you have met the requirement.

**Comment by bogdanadrianmarc** [comment]
> @bogdanadrianmarc I'm going to need some screenshots/guidance on what you have done here so I can tell if you have met the requirement.

Sure, no worries, here's a screenshot from before:
<img width="764" alt="Screenshot 2024-08-20 at 15 58 11" src="https://github.com/user-attachments/assets/849e400d-16f5-4d6d-ba59-234e6c4602fa">

and after:
<img width="554" alt="Screenshot 2024-08-20 at 15 58 20" src="https://github.com/user-attachments/assets/19f4f3d6-e0a3-495b-9716-86dd5bd180c3">

I've increased the contrast for the search input border, map selection on the right and modal text and buttons.

**Comment by tomguilbert** [comment]
@bogdanadrianmarc - that all looks really great except the 'confirm' button, which still has insufficient contrast I think (it is only 1.59:1)

**Comment by bogdanadrianmarc** [comment]
> @bogdanadrianmarc - that all looks really great except the 'confirm' button, which still has insufficient contrast I think (it is only 1.59:1)

The button is normally disabled, unless a correct location is entered:
<img width="575" alt="Screenshot 2024-08-20 at 16 30 40" src="https://github.com/user-attachments/assets/4b7b5d1e-3714-494d-85e1-ea772cfc9476">

I've tried increasing the contrast but in my opinion it looks too much like it's not actually disabled and can be clicked:
<img width="562" alt="Screenshot 2024-08-20 at 16 32 16" src="https://github.com/user-attachments/assets/002c46d7-a574-4574-bf27-0d5ce4a8d4a6">

@jonrandahl What do you think about this one?

**Comment by jonrandahl** [comment]
@tomguilbert I've done a little research this morning and will action this today.[^1]

<cite>https://advancedbytez.com/make-disabled-buttons-accessible/</cite>
> According to the Web Content Accessibility Guidelines (WCAG), disabled buttons don't need to meet contrast requirements. However, it's recommended to make disabled buttons have a different style from enabled buttons, even for color-blind users. Here are some tips for making disabled buttons more accessible: 
> ## Use of visual indicators
> Use of the CSS property `cursor: not-allowed` for visual users with cognitive impairments. Using this cursor property on a disabled button will provide an additional visual indicator that the button is inactive. 
> ## Use color
>Use saturated colors for primary buttons to create contrast with disabled buttons. You can also try displaying disabled buttons at about 40% opacity of their enabled state. 
> ## Use text
> Make sure the text within the button is always visible, even when disabled. You can also use helpful text to indicate that the button is disabled, such as "disabled" or "not a user error". 
> ## Use other techniques
> You can also try using the `aria-disabled` attribute to signal to assistive technology that a button is disabled. You can also add error messages and feedback to help users understand what's going on. 

[^1]: This would be a good piece of information for other projects as well. TBD

**Comment by tomguilbert** [comment]
@jonrandahl thanks for clarifying that diabled buttons don't need to meet contrast WCAG guidelines (I didn't know that based on Gemma's s/s or Bogdan's response above). In that case, given that we don't have huge budget for this I think we should leave as is unless there is something super easy and simple you can add Jon from your researches?

**Comment by jonrandahl** [comment]
On inspection @tomguilbert we've already implemented the visual indication via cursor, adding the opacity and aria-disabled will be relatively simple, outside of finding where to apply the adjustments, and I will package those up in my latest changes coming!

Edit: It will end up looking like this visually:
![CleanShot 2024-08-22 at 10 34 56](https://github.com/user-attachments/assets/ba3c7ba6-ca8f-433e-8cd0-36cc8f905dda)

**Comment by tomguilbert** [comment]
thanks @jonrandahl

**Comment by tomguilbert** [comment]
@jonrandahl as @DanielCouzens is going to pick up some UKHPI tickets whilst @bogdanadrianmarc is on leave I've assigned this to you, as I think you are dealing with it - please correct if wrong!

**Comment by jonrandahl** [comment]
@tomguilbert for reference, and will update when on dev instance:

![CleanShot 2024-08-28 at 08 50 38](https://github.com/user-attachments/assets/819a3fab-b0fe-4045-ac53-728e0c129190)

![CleanShot 2024-08-28 at 08 53 48](https://github.com/user-attachments/assets/bc975600-1685-4c3a-b744-66331ce67e7c)

![CleanShot 2024-08-28 at 08 54 54](https://github.com/user-attachments/assets/7bf9c1d5-63cc-40f2-affd-146c2552040f)

![CleanShot 2024-08-28 at 09 06 33](https://github.com/user-attachments/assets/8c3d3066-9196-45ce-82d6-a5ad5de4a1cf)

**Comment by tomguilbert** [comment]
@jonrandahl is this ready to test on Dev?

**Comment by jonrandahl** [comment]
@tomguilbert it most certainly is!

https://hmlr-dev-pres.epimorphics.net/app/ukhpi/

**Comment by tomguilbert** [comment]
@jonrandahl when I tab through the 'Show on Map' options I can see them in focus but hitting return doesn't activate them - is it meant to?

**Comment by jonrandahl** [comment]
> @jonrandahl when I tab through the 'Show on Map' options I can see them in focus but hitting return doesn't activate them - is it meant to?

Accessible keyboard navigation action is to press the spacebar, not return, which does select the option tabbed to.

The live site switches via a combination of tab and arrow key presses

**Comment by tomguilbert** [comment]
cool thanks - looks good
