### ISSUE TITLE
UKHPI - 2.4.2: Page Titled

### ISSUE THREAD

**Issue by bogdanadrianmarc** [epimorphics/ukhpi#409]
See https://docs.google.com/spreadsheets/d/1YS3N5ps9pJGFOxBDi9C2DwA37WQPIVax/edit?gid=1215429860#gid=1215429860&range=18:18

**Comment by DanielCouzens** [comment]
There is a PR for common styles to update the title tag please see here https://github.com/epimorphics/lr_common_styles/pull/61

**Comment by bogdanadrianmarc** [comment]
Thanks Dan! UKHPI shouldn't be affected as it appears it isn't even using `lr_common_styles` 🙂
