### ISSUE TITLE
Beta test feedback: selecting dates

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#41]
> 3) View the tables and graphs for North East England sales volumes for 2007 only
> Couldn’t get it to work for 2007date only.  Selecting the region was fine.

> 4) Download in a spreadsheet the HPI, Average price, percentage 
> monthly change and percentage annual change for all property types 
> for Pembrokeshire between April 2014 and April 2015

> Specific dates didn’t work again but everything else was clear and straightforward

> 5) View the tables and graphs for the average prices for the UK over the last 5 years
> Date issue again, everything else okay

Frustratingly, all we know from this user is that selecting dates didn't work. I believe this was Pam White. Would be good for someone to speak to Pam to find out what the issue was.

**Comment by ijdickinson** [comment]
See also action on #40

**Comment by MalcolmShazell** [comment]
can't re-create - no new reports of this - going to close
