### ISSUE TITLE
UKHPI - 2.5.8: Target Size (Minimum)

### ISSUE THREAD

**Issue by bogdanadrianmarc** [epimorphics/ukhpi#411]
See https://docs.google.com/spreadsheets/d/1YS3N5ps9pJGFOxBDi9C2DwA37WQPIVax/edit?gid=1215429860#gid=1215429860&range=20:20

**Comment by tomguilbert** [comment]
Thanks @bogdanadrianmarc - I saw the screenshots so can close this as I have the evidence. I'm also assuming you were adressing row 21 in the sheet.
