### ISSUE TITLE
UKHPI - 2.4.13 Focus Appearance

### ISSUE THREAD

**Issue by bogdanadrianmarc** [epimorphics/ukhpi#412]
See https://docs.google.com/spreadsheets/d/1YS3N5ps9pJGFOxBDi9C2DwA37WQPIVax/edit?gid=1215429860#gid=1215429860&range=22:22

**Comment by tomguilbert** [comment]
@bogdanadrianmarc thanks - I can see your changes via the screenshots, although difficult to know if all the new contrast ratios are compliant. Are you sure these, for instance, work?

![Image](https://github.com/user-attachments/assets/5c79e27d-49ee-4e2d-844d-89497a3e69ec)

![Image](https://github.com/user-attachments/assets/8a0bac37-b4f1-4f59-82de-f7b16c26394b)

**Comment by bogdanadrianmarc** [comment]
> @bogdanadrianmarc thanks - I can see your changes via the screenshots, although difficult to know if all the new contrast ratios are compliant. Are you sure these, for instance, work?
> 
> ![Image](https://private-user-images.githubusercontent.com/97290791/359449713-5c79e27d-49ee-4e2d-844d-89497a3e69ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNjY2NjcsIm5iZiI6MTcyNDE2NjM2NywicGF0aCI6Ii85NzI5MDc5MS8zNTk0NDk3MTMtNWM3OWUyN2QtNDllZS00ZTJkLTg0NGQtODk0OTdhM2U2OWVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDE1MDYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzNWMwYTlmNDFiNmY2N2Y2MzZkZjY1M2E1OWRkNjEyODhjMmU4YTk0N2EwMWIxODU0OTBiNGU1ZTA4NDRmMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PWxdPVj_N4QhHHHoJrM49za_sfMHov6JaQAW4wt4uAc)
> 
> ![Image](https://private-user-images.githubusercontent.com/97290791/359449408-8a0bac37-b4f1-4f59-82de-f7b16c26394b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNjY2NjcsIm5iZiI6MTcyNDE2NjM2NywicGF0aCI6Ii85NzI5MDc5MS8zNTk0NDk0MDgtOGEwYmFjMzctYjRmMS00ZjU5LTgyZGUtZjdiMTZjMjYzOTRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDE1MDYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjYTJhNjA3ZGQxM2I2MDQxNzgzZGEyMjM4MjM4ZWZkZDk1ZmJhN2Y3ZjAyMDFmMzM2ODU5YjA4ZjliODg1ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0SA3UDYkUise-eoeJUjPxKS-fpRnnqhopJfxPw0ZFIE)

I think the second screenshot is ok, for the first one there seems to be a bug where the CSS is applied to the already selected option as well. I created a PR that fixes the issue, when it gets merged you should be able to test this to make sure it works 👍

**Comment by tomguilbert** [comment]
OK looks good thanks Bogdan
