### ISSUE TITLE
UKHPI - 2.5.3 Label in name

### ISSUE THREAD

**Issue by bogdanadrianmarc** [epimorphics/ukhpi#413]
See https://docs.google.com/spreadsheets/d/1YS3N5ps9pJGFOxBDi9C2DwA37WQPIVax/edit?gid=1215429860#gid=1215429860&range=23:23

**Comment by tomguilbert** [comment]
@bogdanadrianmarc I think the requirement also suggests changing the aria label for the 'use the SPARL form' link as well.

**Comment by DanielCouzens** [comment]
This is in review PR https://github.com/epimorphics/ukhpi/pull/429
