### ISSUE TITLE
UKHPI - 3.2.3: Consistent Navigation

### ISSUE THREAD

**Issue by bogdanadrianmarc** [epimorphics/ukhpi#414]
See https://docs.google.com/spreadsheets/d/1YS3N5ps9pJGFOxBDi9C2DwA37WQPIVax/edit?gid=1215429860#gid=1215429860&range=24:24

**Comment by bogdanadrianmarc** [comment]
@tomguilbert The requirement for this ticket is to have consistent navigation elements across all HMLR applications. But, as mentioned in the FE planning meeting, this is not a HMLR service and naturally has different navigation elements compared to the other services. Another challenge with this would be the fact that the logo cannot link to the LR landing page because this is not a HRML app, instead it must link to the UKHPI landing page.

**Comment by tomguilbert** [comment]
Agreed- let's can this one.
