### ISSUE TITLE
UKHPI - 3.2.6: Consistent Help

### ISSUE THREAD

**Issue by bogdanadrianmarc** [epimorphics/ukhpi#415]
See https://docs.google.com/spreadsheets/d/1YS3N5ps9pJGFOxBDi9C2DwA37WQPIVax/edit?gid=1215429860#gid=1215429860&range=27:27

**Comment by bogdanadrianmarc** [comment]
@tomguilbert The requirement for this ticket is to move to `user guide` link from the navigation bar to the top right corner of the main view (near the language selector), to make it so all LR apps are consistent in regards to where the help button is placed. However, for the rest of the LR apps the help button displays a modal, while for UKHPI it is a link to an external PDF which serves as a user guide:

![Image](https://github.com/user-attachments/assets/d658c93f-d960-423c-8a61-1cca04abbd85)

![Image](https://github.com/user-attachments/assets/fa767992-0a08-4969-be60-cf340382ab43)

![Image](https://github.com/user-attachments/assets/610eb8d2-aaab-4916-8c12-4c55a1ad59c7)

![Image](https://github.com/user-attachments/assets/d997acbd-57e4-4b1c-8c06-6e67bc688fb5)

Moving the user guide PDF link near the language selector wouldn't make sense, unless there is support to display PDFs inside a modal, which we do not currently have

**Comment by tomguilbert** [comment]
This feels like it is wrapped up in the 'common navigation' problem we have, with UKHPI being different to the other services? If so then I htink we ignore, and treat UKHPI as a different service to the others.
