### ISSUE TITLE
UKHPI - 4.1.2: Name, Role, Value

### ISSUE THREAD

**Issue by bogdanadrianmarc** [epimorphics/ukhpi#416]
See https://docs.google.com/spreadsheets/d/1YS3N5ps9pJGFOxBDi9C2DwA37WQPIVax/edit?gid=1215429860#gid=1215429860&range=29:29

**Comment by bogdanadrianmarc** [comment]
I suspect this was more of an issue for other HMLR apps. I double checked all the forms and each input is contained within a `<label>` tag, which means a screen reader will read the label when the input is focused. However, I corrected the aria-label for the select location input as it contained a typo

**Comment by tomguilbert** [comment]
To clarify this one - there is a failure in UKHPI but it is only visible if you compare locations and then remove one of the countries. After doing this you get an 'add location' button. From Gemma:

> it’s not visible unless you get rid of a location and then the add location button appears on the HPI page. I think it was this that was referring to.
>It’s flagged up because the form control does not have a properly associated text label .
```
<li class=“c-compare__add-location”>
Add another location:
<input name=“location-term” type=“text”>
<button name=“form-action” type=“submit” value=“search”>
search
</button>
```


![Image](https://github.com/user-attachments/assets/0b333053-8534-44f5-8065-8fe8d4eb2c0d)

**Comment by tomguilbert** [comment]
@DanielCouzens I think you were working on this last week? That's why I've assigned you but please correct if I'm mistaken.

**Comment by DanielCouzens** [comment]
This is in review https://github.com/epimorphics/ukhpi/pull/432

**Comment by DanielCouzens** [comment]
This has been merged into main. @tomguilbert 

So the error should no longer show when checking fields via silktide.

**Comment by tomguilbert** [comment]
yep looks good thanks @DanielCouzens
