### ISSUE TITLE
Beta test feedback: missing download values?

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#42]
> 6) Determine the average price for detached, semi detached, terraced and 
> flats for Wales in June 2015
>
> When I downloaded as a spreadsheet only downloaded the av price 
> of a flat/maisonette not the 3 other requests above

Also Pam White. We need more details on what went wrong here.

**Comment by ijdickinson** [comment]
Possible that this is an issue with the beta server that is already fixed in dev.

**Comment by ijdickinson** [comment]
@MalcolmShazell to clarify with user whether this is still an issue

**Comment by ijdickinson** [comment]
@MalcolmShazell Shall we bump this to the after-launch milestone? Seems unlikely we'll be able to resolve it today.

**Comment by MalcolmShazell** [comment]
yup - sounds like a plan

**Comment by MalcolmShazell** [comment]
issue has gone away
