### ISSUE TITLE
Beta test feedback: blurred text

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#43]
> 1)	View the tables and graphs for the HPI for England only 
> for all property types for Jan 2011 – December 2015.  
> This was easy to use. I liked the formatting of the date selection. 
> Graphs are a bit basic looking and text slightly blurred other than titles.

I have no idea how to interpret "graphs are a bit basic". This was from the first tranche of user feedback, I don't know who the tester was.

**Comment by ijdickinson** [comment]
May be a browser issue - @MalcolmShazell reports that the text is sharper in MS Edge. @ijdickinson to also look at SVG anti-aliasing settings

**Comment by MalcolmShazell** [comment]
no one has reported this as an issue - shall close
