### ISSUE TITLE
UI update - checkbox instead of images

### ISSUE THREAD

**Issue by DanielCouzens** [epimorphics/ukhpi#431]
Update UI - Please see the spreadsheet https://docs.google.com/spreadsheets/d/1YS3N5ps9pJGFOxBDi9C2DwA37WQPIVax/edit?gid=1215429860#gid=1215429860&range=A7

**Comment by DanielCouzens** [comment]
This is in review. PR https://github.com/epimorphics/ukhpi/pull/434

**Comment by tomguilbert** [comment]
Looks good thanks Dan
