### ISSUE TITLE
Translate screenreader text to welsh

### ISSUE THREAD

**Issue by DanielCouzens** [epimorphics/ukhpi#435]
The following text for screenreaders needs to be translated into Welsh.

_The table has an unusual structure. Please use the second tab in the tablist named 'See data table' for data that is in an accessible format._

**Comment by tomguilbert** [comment]
Translation is:

Mae gan y tabl strwythur anarferol. Defnyddiwch yr ail dab yn y rhestr o dabiau o’r enw ‘Gweler y tabl data’ am ddata sydd mewn fformat hygyrch.

**Comment by DanielCouzens** [comment]
this is in review - PR https://github.com/epimorphics/ukhpi/pull/450

**Comment by DanielCouzens** [comment]
@tomguilbert this is merged into Main.

**Comment by tomguilbert** [comment]
great thanks Dan
