### ISSUE TITLE
Beta-test feedback: graph lines thin and colours not distinct

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#44]
> 2) Download in a spreadsheet – Perth and Kinross averages prices 
> for detached houses and the monthly percentage change for 2014 
> On this it isn’t clear whether the month selected is inclusive ( need to run 
> Jan 14-to Jan 15 rather than Jan 14-Dec 14 which would only include 
> up to 01/12/2014) Cv loaded quickly and was easy to use. As a side note 
> however re the graphs showing changes, I think the colours are too similar, 
> green and blue both thin and pale.

**Comment by ijdickinson** [comment]
Re: date selection, the behaviour is consistent with the old HPI site and we have received no other feedback that the current behaviour is unexpected.

**Comment by ijdickinson** [comment]
@ijdickinson to investigate a different, more distinguishable colour pallette

**Comment by ijdickinson** [comment]
Tweaked colours and line weights

**Comment by MalcolmShazell** [comment]
confirm this has fixed the problem
