### ISSUE TITLE
Beta test feedback: monthly change

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#45]
> 4)	Download in a spreadsheet the HPI, Average price, percentage monthly 
> change and percentage annual change for all property types for 
> Pembrokeshire between April 2014 and April 2015. 
> Spreadsheet only shows monthly change header as ‘percentage change’ doesn’t specify as monthly.

**Comment by ijdickinson** [comment]
I will use the `period duration` attribute on the data to add some distinguishing text for quarterly values, and make the CSV columns more clearly labelled.

**Comment by ijdickinson** [comment]
Forgot to tag commit 077b017a35b9c809a408740e3c136a80c5a13367 for this ticket

**Comment by ijdickinson** [comment]
I have:

* added a note to the graphs when the figures are reported quarterly not monthly
* added a reporting period to the spreadsheet
* amended the spreadsheet to say either `percentageChangeMonthly` or `percentageChangeQuarterly`

**Comment by ijdickinson** [comment]
@bwmcbride pointed out that the graph caption for monthly change currently says "percentage monthly change". It should change to "percentage quarterly change" for NI regions

**Comment by ijdickinson** [comment]
Updated to address the bug that Brian spotted

**Comment by MalcolmShazell** [comment]
confirm fixed for UK monthly and NI quaterly
