### ISSUE TITLE
Beta-test feedback: flashing text

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#46]
> 6)	Determine the average price for detached, semi detached, 
> terraced and flats for Wales in June 2015. 
> This was easy enough to do however  data appearing in text 
> above graph but flashed on/off when trying to highlight/copy and 
> then disappeared off to the left of the screen (see attachment)

This was from the first tranche of feedback. Might be worth checking with the user what platform and browser they were using?

**Comment by ijdickinson** [comment]
@MalcolmShazell  investigating.

**Comment by MalcolmShazell** [comment]
I have not been able to re-create this nor have any other users - closing
