### ISSUE TITLE
Beta-test feedback: meaning of GSS

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#49]
> what is the definition of GSS?

**Comment by skwlilac** [comment]
FWIW GSS stands for Government Statistical Services. ONS documentation of the structure and allocation of GSS geography codes and related policies can be found at:

https://geoportal.statistics.gov.uk/Docs/Coding_and_Naming_Policy_for_UK_Statistical_Geographies.zip

and 

https://geoportal.statistics.gov.uk/Docs/GSS_Geography_Policy_V2_(Mar_2015).zip

The former is probably a more useful read.

HTH

**Comment by ijdickinson** [comment]
@MalcolmShazell to add the appropriate documentation to the help page

**Comment by ijdickinson** [comment]
Thanks @skwlilac. It wasn't that we didn't know the answer: the feedback from the user was that the column on the download spreadsheet doens't explain what a GSS code is. The resolution is that we're going to make it clear in the help file. Sorry for not adding more context!

**Comment by ijdickinson** [comment]
We have a help file now, but there wasn't time to document all of the features. So specifically the meaning of a GSS code in the CSV download is not explained.

**Comment by MalcolmShazell** [comment]
No one has complained - I suspect users are more likely to google 'gss code' than look in our help file
