### ISSUE TITLE
united kingdom data not displaying

### ISSUE THREAD

**Issue by MalcolmShazell** [epimorphics/ukhpi#5]
Using Firefox 46.0.1
When looking at countries - method
select wales - see wales data
select united kingdom - data does not update.

this only appears to be a problem with united kingdom
select wales - see wales data
select north-east - see north-east data

**Comment by ijdickinson** [comment]
I think this was a problem with the old data. It should be fixed now, if you can confirm?

**Comment by MalcolmShazell** [comment]
confirm fixed
