### ISSUE TITLE
Update qonsole sample queries

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#51]

**Comment by bwmcbride** [comment]
Is this  a duplicate of https://github.com/epimorphics/lr-landing/issues/1

**Comment by ijdickinson** [comment]
Actually that may be un Herring Rouge (gitlab, not github)

**Comment by bwmcbride** [comment]
I or you can just delete the old one if that's easier

**Comment by ijdickinson** [comment]
It's easier to leave that other ticket in place so that I can properly associate the commit with the issue. Update deployed now.

**Comment by MalcolmShazell** [comment]
confirm done
