### ISSUE TITLE
Consistent primary verb

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#52]
We should be consistent about which verb we suggest to the user that they are performing:

* search the UKHPI
* browse the UKHPI
* explore the UKHPI

**Comment by ijdickinson** [comment]
Some history: in the old HPI app we started off with 'explore', but we were asked by LR comms to change it to 'search' on the landing page, on the basis (as far as I can recall) that searching is a more familiar action to users. The current landing page copy follows that previous tradition. Stephanie has suggested that explore or browse might be a better fit with the actual task.

**Comment by ijdickinson** [comment]
I've deployed an update which removes the primary verb from the main app page - it was a bit unnecessary anyway. This gave the opportunity to simplify the heading a bit.

**Comment by ijdickinson** [comment]
Comment from Stephanie on the latest change:

> Hi Ian, it looks much better and more consistent,

**Comment by marklunn** [comment]
@ijdickinson looks good to me and I'm happy to close unless you are planning any further updates on this?

**Comment by ijdickinson** [comment]
@marklunn I'm not planning any changes at the moment, but I'd like Liz to comment on Stephanie's suggestions and say that she's happy with where we are (or not!)

**Comment by MalcolmShazell** [comment]
Liz has updated - she is happy
