### ISSUE TITLE
After selecting from and to dates when i select a new from date i can't select a date after the previous to date

### ISSUE THREAD

**Issue by marklunn** [epimorphics/ukhpi#53]
For example: If I select 2014-01 - 2015-01, when I then try and conduct a new search I'm unable to select a 'From' date that is beyond 2015-01.

I know this is a fix for not being able to select a 'To' date prior to the 'From' date, so I'm not sure if this can be changed?  Or if users will just have to select the 'To' date first when conducting a new search?

**Comment by ijdickinson** [comment]
Yes, this is by design. The only thing we could do is add a separate 'reset search' option. Even with a reset button, the app will still have the same behaviour, but it's less apparent because the default 'to' date is the current month.

**Comment by MalcolmShazell** [comment]
Working as intended - again users have had no problem with the current functionality
