### ISSUE TITLE
graph display 'ignores' dates with no data

### ISSUE THREAD

**Issue by MalcolmShazell** [epimorphics/ukhpi#54]
Ian, If you select and NI region and a date range starting where there is no data and going into a place where there is f.ex Jan 2000 - jan 2016 graph starts at 2005 is this intentional?

It confused me slightly when I first looked at it as I thought the program had bugged out - don't think its major and certainly doesn't need looking at until after go live and then only if we have queries on it

**Comment by ijdickinson** [comment]
The graph axis extent is current set from the data, not the dates on the form. I could change that, but at the moment you get the range that's in the data. 

If we do change it, one effect will be to have a blank margin on the right of the graph. The default 'to' date in the form is 'today', and there's never a case when the latest published data goes all the way up to today.

**Comment by MalcolmShazell** [comment]
Thanks Ian - Solves my question - probably better to see if it causes problems to the users before looking further at this.
