### ISSUE TITLE
Returning from multi column table view button disappears when clicking 'Show multi-column table view'

### ISSUE THREAD

**Issue by marklunn** [epimorphics/ukhpi#56]

**Comment by ijdickinson** [comment]
@marklunn @MalcolmShazell I've assigned this to the after-launch milestone, since I'm not sure it's crucial to get it fixed today. Please feel free to bump the priority if you think it's more urgent than that.

**Comment by MalcolmShazell** [comment]
@ijdickinson @marklunn I think we leave this - better to keep the code stable than risk adding a different bug

**Comment by ijdickinson** [comment]
Fix deployed

**Comment by marklunn** [comment]
switching table view button functions properly and doesn't disappear. Happy to close
