### ISSUE TITLE
IE 11 has stopped working

### ISSUE THREAD

**Issue by MalcolmShazell** [epimorphics/ukhpi#6]
when using IE11 the main page is displayed but when you select 'change selection'
you get the message
epimorphics has stopped responding due to a long running script.

**Comment by ijdickinson** [comment]
Hi Mal,
This appears to have been a problem with a particular UK geoJSON file I was loading at the background layer for the map, causing LeafletJS to go into a busy loop. I think I've solved it by upgrading to a later version of leafletJS, if you'd like to confirm.

**Comment by MalcolmShazell** [comment]
I'm afraid the problem is still there Ian

**Comment by ijdickinson** [comment]
Are you looking at `dev

**Comment by MalcolmShazell** [comment]
stupid bookmarks - know I shouldn't have come in today :( - yeah its fixed sorry
