### ISSUE TITLE
Redirection page for old HPI users

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#60]
We currently have it set up that users arriving at the old HPI page will be redirected immediately to the new UKHPI tool. After discussion, we have decided to add an interim page to explain the change, but which automatically redirects to the new page.

**Comment by ijdickinson** [comment]
I've added a jump page:

    /app/root/landing/hpi

I realise the URL is a bit clunky, but it only appears for a short time. Brian - can you please arrange to have `/app/hpi` and `/app/hpi/` redirect to this page, which should then automatically redirect to the UKHPI page.

**Comment by bwmcbride** [comment]
Just confirming that the requirement is to *route* /app/hpi to /app/root/landing/hpi, in a similar manner to the way /app/docs/*is routed to /app/root/doc/*

The difference is that the user will not see /app/root/landing/hpi in their browser bar.

**Comment by ijdickinson** [comment]
Yes, that's correct. Thank you, and I will try to be more precise in future!
