### ISSUE TITLE
When rendering landing page, if no data currently in triple store get error 500

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#62]
This can occur when the service data-store is being rebuilt

Log entry: 

    I, [2016-07-19T08:20:18.872084 #4302]  INFO -- :   Rendered landing/index.html.haml within layouts/application (1.1ms)
    I, [2016-07-19T08:20:18.872224 #4302]  INFO -- : Completed 500 Internal Server Error in 25ms
    F, [2016-07-19T08:20:18.873477 #4302] FATAL -- : 
    ActionView::Template::Error (undefined method `symbolize_keys' for nil:NilClass):
        14:   %p
        15:     As of
        16:     %span.c-headline-figure
        17:       = @landing_state.period
        18:     the average house price in the UK is
        19:     %span.c-headline-figure
        20:       = succeed "," do
      app/presenters/landing_state.rb:12:in `result'
      app/presenters/landing_state.rb:17:in `period'
      app/views/landing/index.html.haml:17:in `_app_views_landing_index_html_haml___4385393609063320877_17597800'

**Comment by ijdickinson** [comment]
@MalcolmShazell @bwmcbride This might be hard to test! Shall we just close it, and re-open if we find that it's an issue in future?

**Comment by MalcolmShazell** [comment]
concur - so long as @bwmcbride is happy

**Comment by ijdickinson** [comment]
Brian confirmed on Slack that he's happy for us to close this issue.
