### ISSUE TITLE
Internet Explorer 11, when the Style is set to 'No Style' and then you try and select some dates there is a random display of dates

### ISSUE THREAD

**Issue by marklunn** [epimorphics/ukhpi#63]
![date issue](https://cloud.githubusercontent.com/assets/13219344/17031375/c12a75d8-4f6b-11e6-85a6-2c6630026c61.PNG)

**Comment by MalcolmShazell** [comment]
Is anyone likely to do this?

**Comment by ijdickinson** [comment]
I assumed it was part of the accessibility tests. Turning off CSS is one of the things tested, but it remains to be seen if we can do anything about it.

**Comment by ijdickinson** [comment]
@marklunn @MalcolmShazell I'm assuming this will get subsumed into the new round of accessibility tests?

**Comment by MalcolmShazell** [comment]
yup
