### ISSUE TITLE
Tyne and Wear does not show on counties map

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#64]
On the counties view, the Tyne and Wear region does not show because the GSS code E11000007 does not match the code E11000004 used in the ONS shape file. We have determined that the code has changed, and E11000007 is correct, so the root issue is that we do not have a shapefile that contains a boundary with the correct identifier.

**Comment by MalcolmShazell** [comment]
confirm T&W can now be selected on the map (assuming you know where it is)
