### ISSUE TITLE
http://lr-pres-dev-c.epimorphics.net/app/ukhpi

### ISSUE THREAD

**Issue by bwmcbride** [epimorphics/ukhpi#65]
http://lr-pres-dev-c.epimorphics.net/app/ukhpi

Browser console reports:

application-2993b7c….js:221 Uncaught TypeError: r is not a constructor

This may not be new - it showed up because I'm switching the integration test to a faster capybara driver which by default fails a test if there is a javascript error.

I can tell the driver to ignore javascript errors, which I will do in the interim.  But if we would like the integration tests to catch such javascript errors then I will turn on detection and this one needs fixed.

**Comment by ijdickinson** [comment]
I've pushed a fixed version to master and dev branches.

**Comment by bwmcbride** [comment]
Confirm fixed on dev
