### ISSUE TITLE
DEFAULT.QC_Accessibility_Eservices - Defect # 487 - HTML validation issues

### ISSUE THREAD

**Issue by MalcolmShazell** [epimorphics/ukhpi#66]
Accessibility Tests were on landing page - following errors highlighted
[defect487.docx](https://github.com/epimorphics/ukhpi/files/415255/defect487.docx)

**Comment by ijdickinson** [comment]
Anticipated fix: remove code

**Comment by ijdickinson** [comment]
Results of validation test on landing page:

    ian@ian-desktop $ curl http://localhost:3000 | tidy5 -e
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100 18319  100 18319    0     0  56398      0 --:--:-- --:--:-- --:--:-- 56540
    Info: Document content looks like XHTML5
    No warnings or errors were found.

    About HTML Tidy: https://github.com/htacg/tidy-html5
    Bug reports and comments: https://github.com/htacg/tidy-html5/issues
    Or send questions and comments to: https://lists.w3.org/Archives/Public/public-htacg/
    Latest HTML specification: http://dev.w3.org/html5/spec-author-view/
    Validate your HTML documents: http://validator.w3.org/nu/
    Lobby your company to join the W3C: http://www.w3.org/Consortium

**Comment by ijdickinson** [comment]
Fixed version on `lr-pres-dev-c`

**Comment by MalcolmShazell** [comment]
fixed - closed
