### ISSUE TITLE
Logo's on landing page on Android phone are very close together

### ISSUE THREAD

**Issue by marklunn** [epimorphics/ukhpi#7]
Can the vertical separation of the logos be increased to make it easier to distinguish between them, thanks.

**Comment by marklunn** [comment]
![screenshot_20160525-100042](https://cloud.githubusercontent.com/assets/13219344/15534908/077341ae-2263-11e6-8dee-f4c10bf8a06a.png)

**Comment by ijdickinson** [comment]
Need to check if this is still an open issue.

**Comment by MalcolmShazell** [comment]
@ijdickinson chrome on my android is still doing this - we can bring it in as a user story to work out the best way to fix this in the refresh

**Comment by ijdickinson** [comment]
@MalcolmShazell Agreed.

**Comment by MalcolmShazell** [comment]
Closing - picked up in the refresh
