### ISSUE TITLE
DEFAULT.QC_Accessibility_Eservices - Defect # 493 - site without CSS "does not resemble" site with CSS

### ISSUE THREAD

**Issue by marklunn** [epimorphics/ukhpi#71]
Description: 
From the accessibility toolbar 'Select' CSS then Disable CSS. Visually check the page still makes sense and is still usable.

Expected: 
Page still conveys its original meaning and can still be used.

Page still makes sense to the reader.

Actual: 
page returned does not resemble the page displayed to the user, the page appears to contain all of the potential search criteria that the user accesses using the change selection button.

A user with CSS disabled would have great difficulty with this page.

**Comment by marklunn** [comment]
![bug_493_clb_picture_153](https://cloud.githubusercontent.com/assets/13219344/17769861/abc15afe-6532-11e6-8adf-ad5da628f220.jpeg)
![bug_493_clb_picture_154](https://cloud.githubusercontent.com/assets/13219344/17769860/abc0d82c-6532-11e6-9121-6568d2871e28.jpeg)
![bug_493_clb_picture_155](https://cloud.githubusercontent.com/assets/13219344/17769857/abbbf186-6532-11e6-92ed-d53473ea2102.jpeg)
![bug_493_clb_picture_156](https://cloud.githubusercontent.com/assets/13219344/17769858/abbcf5ea-6532-11e6-806f-0280fc5d786f.jpeg)
![bug_493_clb_picture_157](https://cloud.githubusercontent.com/assets/13219344/17769859/abbdbcaa-6532-11e6-8c7c-bf0c1cdb9d7d.jpeg)
![bug_493_clb_picture_158](https://cloud.githubusercontent.com/assets/13219344/17769863/abcf61da-6532-11e6-8c7b-2254ea005908.jpeg)
![bug_493_first section of css disabled](https://cloud.githubusercontent.com/assets/13219344/17769864/abd2bf06-6532-11e6-8b57-54e5f1144419.jpeg)
![bug_493_screen before disable css](https://cloud.githubusercontent.com/assets/13219344/17769865/abd63a5a-6532-11e6-8b81-62cc23bf4c25.jpeg)

**Comment by ijdickinson** [comment]
I don't see that it is possible to provide an experience that works with JavaScript disabled, and provides a satisfactory user experience for the majority of users, and make the app workable with CSS disabled. A business decision will be required to meet this criterion; most probably it would mean creating an alternative application for use with screen readers.

**Comment by MalcolmShazell** [comment]
closed due to re-design - have raised this a a general issue for discussion prior to development on the redesign starting
