### ISSUE TITLE
DEFAULT.QC_Accessibility_Eservices - Defect # 496 - table scope and summary

### ISSUE THREAD

**Issue by marklunn** [epimorphics/ukhpi#74]
Description: 
Check that tables have been used correctly.

Refresh the screen.

From the Accessibility toolbar 'select' Tables then Show Data Tables

Expected: 
Grid displayed showing all summary and id information for the table and table cells. 

If tables exist and any of the summary/scope or id's are missing this test fails.

If no table exists on the page 'No Table elements found' is displayed.

UPDATE for HTML 5:
Table summaries will not show.  If table appears to have no summary you will need to disable css then show tables.

Actual: 
Table has no summary and has no id's or scope.

**Comment by marklunn** [comment]
![bug_496_clb_picture_126](https://cloud.githubusercontent.com/assets/13219344/17770125/00fe19ac-6534-11e6-8ce9-d90b25e95f4d.jpeg)
![bug_496_clb_picture_163](https://cloud.githubusercontent.com/assets/13219344/17770128/01b6aea4-6534-11e6-9dc4-0b1935912a3f.jpeg)
![bug_496_clb_picture_165](https://cloud.githubusercontent.com/assets/13219344/17770126/0133758e-6534-11e6-9018-bf05474a5fba.jpeg)

**Comment by ijdickinson** [comment]
Anticipated fix: add scope and summary elements to HTML generator

**Comment by MalcolmShazell** [comment]
Ian - is this something that can be added during the redesign process?

**Comment by ijdickinson** [comment]
@MalcolmShazell yes. 

I'd expect this to be re-tested as part of the a11y testing process for the updated system anyway.

**Comment by MalcolmShazell** [comment]
closed, to be incorporated in the re-design
