### ISSUE TITLE
DEFAULT.QC_Accessibility_Eservices - Defect # 505 - colour contrast

### ISSUE THREAD

**Issue by marklunn** [epimorphics/ukhpi#78]
Description: 
Check that colour contrasts on the screen have sufficient contrast.

From Accessibility toolbar 'Select' Colour then Juicy Studio Contrast Analyser then Contrast Analyser All Tests

Expected: 
A new window will open with a title of Colour Contrast Analyser. 

The new window will display a tabular report.

Check the report for any rows highlighted in yellow.

There are 3 exclusion rows that may be identified in the report, check that they match the attached document and if they do the test passes. (Green text on grey image and maroon text on grey image)
#516714   #eaeaea
#990000   #cdcdcd
#990000   #d7d7d8

Any other fails returned in the report should have a defect raised.

Actual: 
Single failure.  Report attached.

**Comment by marklunn** [comment]
![bug_505_clb_picture_176](https://cloud.githubusercontent.com/assets/13219344/17770345/eadbf134-6534-11e6-994b-904efdbbb9b0.jpeg)
[BUG_505_Colour Contrast Analyser - data selection page.docx](https://github.com/epimorphics/ukhpi/files/424628/BUG_505_Colour.Contrast.Analyser.-.data.selection.page.docx)

**Comment by ijdickinson** [comment]
@marklunn I can't tell which element is failing

**Comment by ijdickinson** [comment]
@marklunn Can you also clarify the difference between this issue and #70 please?

**Comment by marklunn** [comment]
All this is is that the orange colour needs to be tweaked slightly to meet the standard.  This is the same as defect #70

**Comment by ijdickinson** [comment]
@marklunn Sorry, I'm still a bit confused. There are three places where orange is used:

* the background to the BETA badge
* the highlight colour for the current focus element
* one of the line colours on the graph elements

I can't tell from the screenshot which of these is being referred to. The first two are defined by the GDS common stylesheets, so I'm not sure we should be changing those arbitrarily.

**Comment by marklunn** [comment]
It's the background to the BETA badge, but if it's defined by the GDS stylesheets then I guess it's something we shouldn't be changing unless Lorna thinks we should?

**Comment by MalcolmShazell** [comment]
I will take this as an issue to query with GDS. suggest we leave the beta button the way it is for the mo.

**Comment by ijdickinson** [comment]
@MalcolmShazell GDS have already responded to criticism on this issue. The new alpha and beta buttons have a single white-on-blue colour scheme
