### ISSUE TITLE
Overlap at the bottom of the data table on Android phone

### ISSUE THREAD

**Issue by marklunn** [epimorphics/ukhpi#8]
![screenshot_20160525-100145](https://cloud.githubusercontent.com/assets/13219344/15534881/f51544b2-2262-11e6-9dd5-bc28d5c37fa1.png)

**Comment by MalcolmShazell** [comment]
this appears to be affecting MS edge as well appears to crop up when changing the number of items in the selection i.e. adding all the different house types the number of pages in the list expands and causes the overlap

**Comment by marklunn** [comment]
overlap has gone, happy to close
