### ISSUE TITLE
DEFAULT.QC_Accessibility_Eservices - Defect # 507 - list tags

### ISSUE THREAD

**Issue by marklunn** [epimorphics/ukhpi#80]
Description: 
From the Accessibility toolbar 'select' CSS and disable CSS then from the Accessibility toolbar 'select' Structure then List Items

Visually check the page for items that are lists. These can be vertical or horizontal.

Radio buttons should be coded as list items unless they appear within a table - step 2 checks for this.

Expected: 
All items that are lists are enclosed with <li> tags e.g. <li>item</li>.

DO NOT refresh page.

Actual: 
Selection criteria needs list tags.

**Comment by marklunn** [comment]
![bug_507_clb_picture_140](https://cloud.githubusercontent.com/assets/13219344/17770396/385919c8-6535-11e6-9469-51bae4ce4105.jpeg)
![bug_507_clb_picture_177](https://cloud.githubusercontent.com/assets/13219344/17770398/3a5b2a86-6535-11e6-8fbd-31776ea6031f.jpeg)

**Comment by ijdickinson** [comment]
@marklunn This is a bit unclear. I think you're saying that the indicators and property categories should be lists, but not why. Can you confirm, and can you say what the rationale is?

**Comment by marklunn** [comment]
This is where it groups together things like check boxes and radio buttons in lists for the user when CSS is disabled, to make it easier for certain users to identify all of the respective inputs needed.

**Comment by MalcolmShazell** [comment]
closed and deferred  to the re-design discussion
