### ISSUE TITLE
DEFAULT.QC_Accessibility_Eservices - Defect # 511 - apply old style document heading nesting

### ISSUE THREAD

**Issue by marklunn** [epimorphics/ukhpi#82]
Description: 
Examine the outline view to ensure that: 

Headings and Page Title are present, 
The headings are nested correctly, and 
The headings provide an effective overview of the contents of the page.

Expected: 
Heading structure is correct. 

Remember to close the outline view window.

Actual: 
Headings are incorrectly nested, H1 heading has 2 instances.

**Comment by marklunn** [comment]
![bug_511_clb_picture_144](https://cloud.githubusercontent.com/assets/13219344/17771618/e20e3ec0-653b-11e6-9e55-f23fdad93dd7.jpeg)
![bug_511_clb_picture_175](https://cloud.githubusercontent.com/assets/13219344/17771620/e432f2e0-653b-11e6-8566-8504a6a967fd.jpeg)

**Comment by ijdickinson** [comment]
Anticipated fix: restructure document to not follow new HTML5 document context rules

**Comment by MalcolmShazell** [comment]
Will raise this as an issue in the project - do HTML5 rules trump this accessibility criteria?

**Comment by ijdickinson** [comment]
@MalcolmShazell Recent discussion I've seen on accessibility forums is that, even though HTML5 encourages multiple hierarchies of headers with sections, it's still easier for screen readers if there's a strict hierarchy starting at `h1`. So, notwithstanding that the standard has moved on, I think we should test to strict nesting.
