### ISSUE TITLE
DEFAULT.QC_Accessibility_Eservices - Defect # 513 - external link indication

### ISSUE THREAD

**Issue by marklunn** [epimorphics/ukhpi#83]
Description: 
If the link opens in a new window, check that the link has the new window icon and tooltips text to warn the user. 

If in doubt check the clarification in the comments of this test.

Expected: 
New window links are correctly identified.

Actual: 
feedback link opens in new window without warning

**Comment by marklunn** [comment]
![bug_513_clb_picture_145](https://cloud.githubusercontent.com/assets/13219344/17776500/c8e71070-6554-11e6-880f-1f43dc997f74.jpeg)

**Comment by ijdickinson** [comment]
Anticipated fix: apply `rel=external`

**Comment by ijdickinson** [comment]
Fixed version on `lr-pres-dev-c`

**Comment by MalcolmShazell** [comment]
oops - closed due to re-design. Looks like for some reason we missed picking up the testing of this fix
