### ISSUE TITLE
UK HPI Home icon on Internet Explorer showing incorrectly

### ISSUE THREAD

**Issue by marklunn** [epimorphics/ukhpi#88]
The UK HPI home icon on the main page layout is too big so the text runs on to the next line.

Screenshot attached

**Comment by marklunn** [comment]
![uk hpi icon](https://cloud.githubusercontent.com/assets/13219344/17886353/45654190-6919-11e6-95b6-5d512e02e621.PNG)

**Comment by marklunn** [comment]
For reference, this is how it looks on Chrome and Firefox
![ff and chrome](https://cloud.githubusercontent.com/assets/13219344/17886397/80a55362-6919-11e6-90f1-fb5c13b2f962.PNG)

**Comment by ijdickinson** [comment]
@marklunn @MalcolmShazell Any more details on reproducing this? On my IE edge it looks fine. Does this occur on a specific version of IE, or do I need to do something else to provoke it?

**Comment by ijdickinson** [comment]
Actually, it's OK - I've found that I can reproduce it on IE11. I'll try to work on a fix (other than "user should upgrade their browser" :) )

**Comment by ijdickinson** [comment]
@marklunn @MalcolmShazell I can't remember if this has been fixed. I'll leave it open, but it would be good to confirm if it's still an open issue.

**Comment by MalcolmShazell** [comment]
@ijdickinson I'm afraid it is still displaying the oversized icon in IE11. Unfortunately for us we still have to support win 11 so it will need a fix applied a some point in the future - we can schedule it into the work about to start

**Comment by ijdickinson** [comment]
@MalcolmShazell We should definitely support IE 11, so yes, we need to keep this open.

**Comment by MalcolmShazell** [comment]
displaying correctly in the new app
