### ISSUE TITLE
Random data input - no feedback on invalid data

### ISSUE THREAD

**Issue by marklunn** [epimorphics/ukhpi#89]
Description: 
Input incorrect/invalid data into any available fields within the page.
Expected: 
The system should describe the error to the user in text.
Actual: 
The user can input random data into the Location, date and search fields. The system does not feedback the invalid data input to the user in any way.
![bug_504_clb_picture_139](https://cloud.githubusercontent.com/assets/13219344/17935960/1d882bc2-6a15-11e6-94cb-a98fedb14217.jpeg)
![bug_504_dateselectorsno css](https://cloud.githubusercontent.com/assets/13219344/17935961/1fc9dbec-6a15-11e6-914b-9bd25b25c14b.jpeg)
![bug_504_year 0201 selected](https://cloud.githubusercontent.com/assets/13219344/17935964/21b796ce-6a15-11e6-8128-bfde46a1cca9.jpeg)

**Comment by ijdickinson** [comment]
@marklunn What's the difference between #89 and #90 ?

**Comment by marklunn** [comment]
Only a slight difference as this one just covers the fact there's no error message for invalid data whereas #90 covers the ability to enter random characters.  I should have kept them together really in one issue.

**Comment by MalcolmShazell** [comment]
closed - as need to re-run initial test
