### ISSUE TITLE
No error message when selecting a 'To' date that is prior to the 'From' date

### ISSUE THREAD

**Issue by marklunn** [epimorphics/ukhpi#9]

**Comment by ijdickinson** [comment]
Rather than an error message, I've linked the calendars so it shouldn't be possible to pick an end date that precedes the start.

Doing so, I did uncover a bug with short periods causing x-axis graph labelling issues. Logged as #17

**Comment by marklunn** [comment]
I'm now unable to select an end date that precedes the start so I'm happy to close
