### ISSUE TITLE
Input random characters to date fields

### ISSUE THREAD

**Issue by marklunn** [epimorphics/ukhpi#90]
Description: 
Input incorrect/invalid data into any available fields within the page.
Expected: 
The system should describe the error to the user in text.
Actual:
The date fields are almost selector only but the fields will permit the user to input random characters
![bug_504_dateselectorsno css](https://cloud.githubusercontent.com/assets/13219344/17936019/4ca4ba9c-6a15-11e6-85ed-a422f14de18e.jpeg)
![bug_504_year 0201 selected](https://cloud.githubusercontent.com/assets/13219344/17936024/4ec72c74-6a15-11e6-84c2-91d28f0f322f.jpeg)

**Comment by MalcolmShazell** [comment]
closed as we need to re-pass aginst new build
