### ISSUE TITLE
Changing checkbox selectors - data displayed doesn't match

### ISSUE THREAD

**Issue by marklunn** [epimorphics/ukhpi#91]
Description: 
Input incorrect/invalid data into any available fields within the page.
Expected: 
The system should describe the error to the user in text.
Actual:
The checkbox selectors, if I change the selectors the data displayed does not match the selector fully:
%annual charge selected and system returns Yearly (title and dataset results would benefit if same word used for both) and monthly
![bug_504_dateselectorsno css](https://cloud.githubusercontent.com/assets/13219344/17936068/7a8e3b90-6a15-11e6-856d-7c09d4bdc336.jpeg)
![bug_504_year 0201 selected](https://cloud.githubusercontent.com/assets/13219344/17936071/7cda2b20-6a15-11e6-872f-264d548f32d4.jpeg)

**Comment by ijdickinson** [comment]
The details of this report will be obsoleted by forthcoming changes. However, I think it's worth leaving open to see if a similar issue might arise in future.

**Comment by MalcolmShazell** [comment]
agreed will keep this open for the 2017 refresh work

**Comment by ijdickinson** [comment]
@marklunn @MalcolmShazell Now that we have the new design, is there anything to be carried-over from this test?

**Comment by MalcolmShazell** [comment]
I think we will close this and re-start any accessibility defects
