### ISSUE TITLE
Missing id with for attribute on date selector

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#93]
Factored out from issue #79 (see item 1-5). There is an instance in the code where a descendent `input` element has a parent `label` with a `for` attribute but no matching `id`

**Comment by ijdickinson** [comment]
Fixed version on `lr-pres-dev-c`

**Comment by ijdickinson** [comment]
@marklunn @MalcolmShazell Please confirm and close if appropriate.

**Comment by MalcolmShazell** [comment]
Hi Ian,

I am just about to go through all the open tickets on Git hub to clear things down ready for the new work to start.
I will check all these as well.

Cheers,
M.

**Comment by MalcolmShazell** [comment]
I'm going to close this - it is fixed
