### ISSUE TITLE
Incorrect nesting of article/section context

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#94]
Factored out from issue #79 (item 1-9): nesting of articles and sections is not correct, curently:

```
section
 article
   section
```

Better would be:

```
article
  div
    section
```

**Comment by ijdickinson** [comment]
Would address the following vnu warning:

    :573.13-573.49: info warning: Article lacks heading. Consider using 
    “h2”-“h6” elements to add identifying headings to all articles.

**Comment by ijdickinson** [comment]
@marklunn @MalcolmShazell Please confirm and close if appropriate.

**Comment by MalcolmShazell** [comment]
@ijdickinson happy this is appropriate and to close
