### ISSUE TITLE
NI has changed the name of three of their LA areas

### ISSUE THREAD

**Issue by MalcolmShazell** [epimorphics/ukhpi#95]
We need to reflect this at some point within the app. there is no requirement to hold the old name for the LA we can use the new name to refer back to 2005.
We in LR will need to change the names in the region file and then generate a new .RU file to load into test for Ian to investigate.

**Comment by ijdickinson** [comment]
As an interim solution, @bwmcbride created a SPARQL update file that updates the staging triple store to contain the new data, so that the application's update region generator scripts can be run. The updates were made to `lr-pres-staging-b` on Nov 17th

**Comment by MalcolmShazell** [comment]
so from way back when the following solution was discussed 
Only the labels for the NI regions should be changed (rdfs and skospref) 
This will require work on the LR side altering the code that generates the URIs and Labels, the suggestion was made the region table should include another column for labels as we are breaking the direct match of URI to label for these three regions. This would also make changes to region names easier in the future.

Just to confirm within the .RU file the following will be correct
this stays the same
<http://landregistry.data.gov.uk/data/ukhpi/region/derry-and-strabane/month/2013-07>
and
ukhpi:refRegion                 <http://landregistry.data.gov.uk/id/region/Derry-and-Strabane> ;
changes to 
ukhpi:refRegion                 <http://landregistry.data.gov.uk/id/region/Derry-City-and-Strabane> ;

**Comment by ijdickinson** [comment]
Steph confirmed in an email that, following discussions between @MalcolmShazell and @bwmcbride, the region URIs are not changing, only the labels.

**Comment by ijdickinson** [comment]
@MalcolmShazell The app on http://lr-pres-dev-c.epimorphics.net/app/ukhpi/explore has been updated for you to test.

**Comment by MalcolmShazell** [comment]
Confirm map selection has the correct new names, LA selection has the new names and cannot search on old names. 
SPARQL query still generates using the 'old' name URI as expected.

Tests complete

**Comment by ijdickinson** [comment]
@MalcolmShazell What do you want to do about deploying this change to production? Will need to be coordinated with the change to the data.

(cc @bwmcbride )

**Comment by MalcolmShazell** [comment]
@ijdickinson @bwmcbride I will confirm the next publication of UKHPI data will contain the NI name changes, check all the files we create next month prior to publication - I think publication next month is Tuesday 15th so we'd need to deploy the changes then - unless there is a show stopper at your end that makes that an unacceptable day

**Comment by ijdickinson** [comment]
15th is good for me.

**Comment by ijdickinson** [comment]
@MalcolmShazell This should be live on production now

**Comment by MalcolmShazell** [comment]
Confirm testing complete app search and map are using the correct new names
