### ISSUE TITLE
Reduce amount of data queried by the landing page

### ISSUE THREAD

**Issue by bwmcbride** [epimorphics/ukhpi#97]
Currently, when the UKHPI landing page /app/ukhpi is retrieved, a query is generated that searches for the UK house price indices since 2015 and selects the most recent.

This may have been a minor contributing factor to the high load generated recently when some bad UKHPI data was loaded.

The query could search a more limited range of data, e.g. only the last few months worth.

**Comment by skwlilac** [comment]
The structure of the query in question - given in full below - could be improved to reduce the amount of exploration for optional values by 'boxing' the `FILTER...` and `BIND...` in the trailing part of the query in a BGP with the patterns that precede the first `OPTIONAL`. This would the probing for 49 property values (the optional clauses) prior to filtering, sorting and limiting. 

A more radical alternative also presented below would be to use a nested select to more directly select the (single) *most* recent indices for the given region (`.../united-kingdom` in this case).

## Current WHERE structure
```
WHERE
  { ?item  ukhpi:refMonth   ?ukhpi_refMonth ;
           ukhpi:refRegion  <http://landregistry.data.gov.uk/id/region/united-kingdom>
    OPTIONAL
      { ?item  ukhpi:averagePrice  ?ukhpi_averagePrice }
   ... # 47 omitted optionals
    OPTIONAL
      { ?item  ukhpi:salesVolume  ?ukhpi_salesVolume }
    FILTER ( ?ukhpi_refMonth >= "2015-01"^^xsd:gYearMonth )
    BIND(<http://landregistry.data.gov.uk/id/region/united-kingdom> AS ?ukhpi_refRegion)
  }
ORDER BY DESC(?ukhpi_refMonth)
LIMIT   1
```

### Improved WHERE structure
```
 WHERE
  {  { ?item  ukhpi:refMonth   ?ukhpi_refMonth ;
             ukhpi:refRegion  <http://landregistry.data.gov.uk/id/region/united-kingdom>
           FILTER ( ?ukhpi_refMonth >= "2015-01"^^xsd:gYearMonth )
         BIND(<http://landregistry.data.gov.uk/id/region/united-kingdom> AS ?ukhpi_refRegion)
    }
    OPTIONAL
      { ?item  ukhpi:averagePrice  ?ukhpi_averagePrice }
   ... # 47 omitted optionals
    OPTIONAL
      { ?item  ukhpi:salesVolume  ?ukhpi_salesVolume }
  }
ORDER BY DESC(?ukhpi_refMonth)
LIMIT   1
```

### Alternate WHERE clause structure
```
 WHERE
 { 
   BIND(<http://landregistry.data.gov.uk/id/region/united-kingdom> AS ?ukhpi_refRegion)
   { SELECT   ?item (max(?refMonth) as ?ukhpi_refMonth) WHERE
     { ?item  ukhpi:refMonth   ?refMonth ;
               ukhpi:refRegion  <http://landregistry.data.gov.uk/id/region/united-kingdom> .
      } LIMIT 1
    }
    OPTIONAL
    { ?item  ukhpi:averagePrice  ?ukhpi_averagePrice }
   ... # 47 omitted optionals
    OPTIONAL
    { ?item  ukhpi:salesVolume  ?ukhpi_salesVolume }
 }
ORDER BY DESC(?ukhpi_refMonth)
```

## Full Query 
```
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ukhpi: <http://landregistry.data.gov.uk/def/ukhpi/>
SELECT  ?item ?ukhpi_refMonth ?ukhpi_refRegion ?ukhpi_averagePrice ?ukhpi_averagePriceCash ?ukhpi_averagePriceDetached ?ukhpi_averagePriceExistingProperty ?ukhpi_averagePriceFirstTimeBuyer ?ukhpi_averagePriceFlatMaisonette ?ukhpi_averagePriceFormerOwnerOccupier ?ukhpi_averagePriceMortgage ?ukhpi_averagePriceNewBuild ?ukhpi_averagePriceSA ?ukhpi_averagePriceSemiDetached ?ukhpi_averagePriceTerraced ?ukhpi_housePriceIndex ?ukhpi_housePriceIndexCash ?ukhpi_housePriceIndexDetached ?ukhpi_housePriceIndexExistingProperty ?ukhpi_housePriceIndexFirstTimeBuyer ?ukhpi_housePriceIndexFlatMaisonette ?ukhpi_housePriceIndexFormerOwnerOccupier ?ukhpi_housePriceIndexMortgage ?ukhpi_housePriceIndexNewBuild ?ukhpi_housePriceIndexSA ?ukhpi_housePriceIndexSemiDetached ?ukhpi_housePriceIndexTerraced ?ukhpi_percentageAnnualChange ?ukhpi_percentageAnnualChangeCash ?ukhpi_percentageAnnualChangeDetached ?ukhpi_percentageAnnualChangeExistingProperty ?ukhpi_percentageAnnualChangeFirstTimeBuyer ?ukhpi_percentageAnnualChangeFlatMaisonette ?ukhpi_percentageAnnualChangeFormerOwnerOccupier ?ukhpi_percentageAnnualChangeMortgage ?ukhpi_percentageAnnualChangeNewBuild ?ukhpi_percentageAnnualChangeSemiDetached ?ukhpi_percentageAnnualChangeTerraced ?ukhpi_percentageChange ?ukhpi_percentageChangeCash ?ukhpi_percentageChangeDetached ?ukhpi_percentageChangeExistingProperty ?ukhpi_percentageChangeFirstTimeBuyer ?ukhpi_percentageChangeFlatMaisonette ?ukhpi_percentageChangeFormerOwnerOccupier ?ukhpi_percentageChangeMortgage ?ukhpi_percentageChangeNewBuild ?ukhpi_percentageChangeSemiDetached ?ukhpi_percentageChangeTerraced ?ukhpi_refPeriodDuration ?ukhpi_refPeriodStart ?ukhpi_salesVolume
WHERE
  { ?item  ukhpi:refMonth   ?ukhpi_refMonth ;
           ukhpi:refRegion  <http://landregistry.data.gov.uk/id/region/united-kingdom>
    OPTIONAL
      { ?item  ukhpi:averagePrice  ?ukhpi_averagePrice }
    OPTIONAL
      { ?item  ukhpi:averagePriceCash  ?ukhpi_averagePriceCash }
    OPTIONAL
      { ?item  ukhpi:averagePriceDetached  ?ukhpi_averagePriceDetached }
    OPTIONAL
      { ?item  ukhpi:averagePriceExistingProperty  ?ukhpi_averagePriceExistingProperty }
    OPTIONAL
      { ?item  ukhpi:averagePriceFirstTimeBuyer  ?ukhpi_averagePriceFirstTimeBuyer }
    OPTIONAL
      { ?item  ukhpi:averagePriceFlatMaisonette  ?ukhpi_averagePriceFlatMaisonette }
    OPTIONAL
      { ?item  ukhpi:averagePriceFormerOwnerOccupier  ?ukhpi_averagePriceFormerOwnerOccupier }
    OPTIONAL
      { ?item  ukhpi:averagePriceMortgage  ?ukhpi_averagePriceMortgage }
    OPTIONAL
      { ?item  ukhpi:averagePriceNewBuild  ?ukhpi_averagePriceNewBuild }
    OPTIONAL
      { ?item  ukhpi:averagePriceSA  ?ukhpi_averagePriceSA }
    OPTIONAL
      { ?item  ukhpi:averagePriceSemiDetached  ?ukhpi_averagePriceSemiDetached }
    OPTIONAL
      { ?item  ukhpi:averagePriceTerraced  ?ukhpi_averagePriceTerraced }
    OPTIONAL
      { ?item  ukhpi:housePriceIndex  ?ukhpi_housePriceIndex }
    OPTIONAL
      { ?item  ukhpi:housePriceIndexCash  ?ukhpi_housePriceIndexCash }
    OPTIONAL
      { ?item  ukhpi:housePriceIndexDetached  ?ukhpi_housePriceIndexDetached }
    OPTIONAL
      { ?item  ukhpi:housePriceIndexExistingProperty  ?ukhpi_housePriceIndexExistingProperty }
    OPTIONAL
      { ?item  ukhpi:housePriceIndexFirstTimeBuyer  ?ukhpi_housePriceIndexFirstTimeBuyer }
    OPTIONAL
      { ?item  ukhpi:housePriceIndexFlatMaisonette  ?ukhpi_housePriceIndexFlatMaisonette }
    OPTIONAL
      { ?item  ukhpi:housePriceIndexFormerOwnerOccupier  ?ukhpi_housePriceIndexFormerOwnerOccupier }
    OPTIONAL
      { ?item  ukhpi:housePriceIndexMortgage  ?ukhpi_housePriceIndexMortgage }
    OPTIONAL
      { ?item  ukhpi:housePriceIndexNewBuild  ?ukhpi_housePriceIndexNewBuild }
    OPTIONAL
      { ?item  ukhpi:housePriceIndexSA  ?ukhpi_housePriceIndexSA }
    OPTIONAL
      { ?item  ukhpi:housePriceIndexSemiDetached  ?ukhpi_housePriceIndexSemiDetached }
    OPTIONAL
      { ?item  ukhpi:housePriceIndexTerraced  ?ukhpi_housePriceIndexTerraced }
    OPTIONAL
      { ?item  ukhpi:percentageAnnualChange  ?ukhpi_percentageAnnualChange }
    OPTIONAL
      { ?item  ukhpi:percentageAnnualChangeCash  ?ukhpi_percentageAnnualChangeCash }
    OPTIONAL
      { ?item  ukhpi:percentageAnnualChangeDetached  ?ukhpi_percentageAnnualChangeDetached }
    OPTIONAL
      { ?item  ukhpi:percentageAnnualChangeExistingProperty  ?ukhpi_percentageAnnualChangeExistingProperty }
    OPTIONAL
      { ?item  ukhpi:percentageAnnualChangeFirstTimeBuyer  ?ukhpi_percentageAnnualChangeFirstTimeBuyer }
    OPTIONAL
      { ?item  ukhpi:percentageAnnualChangeFlatMaisonette  ?ukhpi_percentageAnnualChangeFlatMaisonette }
    OPTIONAL
      { ?item  ukhpi:percentageAnnualChangeFormerOwnerOccupier  ?ukhpi_percentageAnnualChangeFormerOwnerOccupier }
    OPTIONAL
      { ?item  ukhpi:percentageAnnualChangeMortgage  ?ukhpi_percentageAnnualChangeMortgage }
    OPTIONAL
      { ?item  ukhpi:percentageAnnualChangeNewBuild  ?ukhpi_percentageAnnualChangeNewBuild }
    OPTIONAL
      { ?item  ukhpi:percentageAnnualChangeSemiDetached  ?ukhpi_percentageAnnualChangeSemiDetached }
    OPTIONAL
      { ?item  ukhpi:percentageAnnualChangeTerraced  ?ukhpi_percentageAnnualChangeTerraced }
    OPTIONAL
      { ?item  ukhpi:percentageChange  ?ukhpi_percentageChange }
    OPTIONAL
      { ?item  ukhpi:percentageChangeCash  ?ukhpi_percentageChangeCash }
    OPTIONAL
      { ?item  ukhpi:percentageChangeDetached  ?ukhpi_percentageChangeDetached }
    OPTIONAL
      { ?item  ukhpi:percentageChangeExistingProperty  ?ukhpi_percentageChangeExistingProperty }
    OPTIONAL
      { ?item  ukhpi:percentageChangeFirstTimeBuyer  ?ukhpi_percentageChangeFirstTimeBuyer }
    OPTIONAL
      { ?item  ukhpi:percentageChangeFlatMaisonette  ?ukhpi_percentageChangeFlatMaisonette }
    OPTIONAL
      { ?item  ukhpi:percentageChangeFormerOwnerOccupier  ?ukhpi_percentageChangeFormerOwnerOccupier }
    OPTIONAL
      { ?item  ukhpi:percentageChangeMortgage  ?ukhpi_percentageChangeMortgage }
    OPTIONAL
      { ?item  ukhpi:percentageChangeNewBuild  ?ukhpi_percentageChangeNewBuild }
    OPTIONAL
      { ?item  ukhpi:percentageChangeSemiDetached  ?ukhpi_percentageChangeSemiDetached }
    OPTIONAL
      { ?item  ukhpi:percentageChangeTerraced  ?ukhpi_percentageChangeTerraced }
    OPTIONAL
      { ?item  ukhpi:refPeriodDuration  ?ukhpi_refPeriodDuration }
    OPTIONAL
      { ?item  ukhpi:refPeriodStart  ?ukhpi_refPeriodStart }
    OPTIONAL
      { ?item  ukhpi:salesVolume  ?ukhpi_salesVolume }
    FILTER ( ?ukhpi_refMonth >= "2015-01"^^xsd:gYearMonth )
    BIND(<http://landregistry.data.gov.uk/id/region/united-kingdom> AS ?ukhpi_refRegion)
  }
ORDER BY DESC(?ukhpi_refMonth)
LIMIT   1
```

**Comment by ijdickinson** [comment]
@skwlilac Thanks. This will need to be cross-referenced in a DSAPI ticket, which is the thing that actually generates the queries.

**Comment by ijdickinson** [comment]
@skwlilac @bwmcbride Now that we have the new version of DsAPI installed and running, the query that is generated for the front-page looks like this (below). Is this a sensible enough query strategy that we can close this issue now?

    PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
    PREFIX  ukhpi: <http://landregistry.data.gov.uk/def/ukhpi/>

    SELECT  ?item ?ukhpi_refMonth ?ukhpi_refRegion ?ukhpi_averagePrice ?ukhpi_averagePriceCash 
    ?ukhpi_averagePriceDetached ?ukhpi_averagePriceExistingProperty ?ukhpi_averagePriceFirstTimeBuyer 
    ?ukhpi_averagePriceFlatMaisonette ?ukhpi_averagePriceFormerOwnerOccupier ?ukhpi_averagePriceMortgage 
    ?ukhpi_averagePriceNewBuild ?ukhpi_averagePriceSA ?ukhpi_averagePriceSemiDetached 
    ?ukhpi_averagePriceTerraced ?ukhpi_housePriceIndex ?ukhpi_housePriceIndexCash ?ukhpi_housePriceIndexDetached 
    ?ukhpi_housePriceIndexExistingProperty ?ukhpi_housePriceIndexFirstTimeBuyer ?ukhpi_housePriceIndexFlatMaisonette 
    ?ukhpi_housePriceIndexFormerOwnerOccupier ?ukhpi_housePriceIndexMortgage ?ukhpi_housePriceIndexNewBuild 
    ?ukhpi_housePriceIndexSA ?ukhpi_housePriceIndexSemiDetached ?ukhpi_housePriceIndexTerraced 
    ?ukhpi_percentageAnnualChange ?ukhpi_percentageAnnualChangeCash ?ukhpi_percentageAnnualChangeDetached 
    ?ukhpi_percentageAnnualChangeExistingProperty ?ukhpi_percentageAnnualChangeFirstTimeBuyer 
    ?ukhpi_percentageAnnualChangeFlatMaisonette ?ukhpi_percentageAnnualChangeFormerOwnerOccupier 
    ?ukhpi_percentageAnnualChangeMortgage ?ukhpi_percentageAnnualChangeNewBuild 
    ?ukhpi_percentageAnnualChangeSemiDetached ?ukhpi_percentageAnnualChangeTerraced ?ukhpi_percentageChange 
    ?ukhpi_percentageChangeCash ?ukhpi_percentageChangeDetached ?ukhpi_percentageChangeExistingProperty 
    ?ukhpi_percentageChangeFirstTimeBuyer ?ukhpi_percentageChangeFlatMaisonette ?ukhpi_percentageChangeFormerOwnerOccupier 
    ?ukhpi_percentageChangeMortgage ?ukhpi_percentageChangeNewBuild ?ukhpi_percentageChangeSemiDetached 
    ?ukhpi_percentageChangeTerraced ?ukhpi_refPeriodDuration ?ukhpi_refPeriodStart ?ukhpi_salesVolume 
    ?ukhpi_salesVolumeCash ?ukhpi_salesVolumeExistingProperty ?ukhpi_salesVolumeMortgage ?ukhpi_salesVolumeNewBuild
    WHERE
      { { SELECT  ?ukhpi_refMonth ?item
          WHERE
            { ?item  ukhpi:refRegion  <http://landregistry.data.gov.uk/id/region/united-kingdom> ;
                     ukhpi:refMonth   ?ukhpi_refMonth
              FILTER ( ?ukhpi_refMonth >= "2015-01"^^xsd:gYearMonth )
            }
          ORDER BY DESC(?ukhpi_refMonth)
          LIMIT   1
        }
        OPTIONAL
          { ?item  ukhpi:averagePrice  ?ukhpi_averagePrice }
        OPTIONAL
          { ?item  ukhpi:averagePriceCash  ?ukhpi_averagePriceCash }
        OPTIONAL
          { ?item  ukhpi:averagePriceDetached  ?ukhpi_averagePriceDetached }
        OPTIONAL
          { ?item  ukhpi:averagePriceExistingProperty  ?ukhpi_averagePriceExistingProperty }
        OPTIONAL
          { ?item  ukhpi:averagePriceFirstTimeBuyer  ?ukhpi_averagePriceFirstTimeBuyer }
        OPTIONAL
          { ?item  ukhpi:averagePriceFlatMaisonette  ?ukhpi_averagePriceFlatMaisonette }
        OPTIONAL
          { ?item  ukhpi:averagePriceFormerOwnerOccupier  ?ukhpi_averagePriceFormerOwnerOccupier }
        OPTIONAL
          { ?item  ukhpi:averagePriceMortgage  ?ukhpi_averagePriceMortgage }
        OPTIONAL
          { ?item  ukhpi:averagePriceNewBuild  ?ukhpi_averagePriceNewBuild }
        OPTIONAL
          { ?item  ukhpi:averagePriceSA  ?ukhpi_averagePriceSA }
        OPTIONAL
          { ?item  ukhpi:averagePriceSemiDetached  ?ukhpi_averagePriceSemiDetached }
        OPTIONAL
          { ?item  ukhpi:averagePriceTerraced  ?ukhpi_averagePriceTerraced }
        OPTIONAL
          { ?item  ukhpi:housePriceIndex  ?ukhpi_housePriceIndex }
        OPTIONAL
          { ?item  ukhpi:housePriceIndexCash  ?ukhpi_housePriceIndexCash }
        OPTIONAL
          { ?item  ukhpi:housePriceIndexDetached  ?ukhpi_housePriceIndexDetached }
        OPTIONAL
          { ?item  ukhpi:housePriceIndexExistingProperty  ?ukhpi_housePriceIndexExistingProperty }
        OPTIONAL
          { ?item  ukhpi:housePriceIndexFirstTimeBuyer  ?ukhpi_housePriceIndexFirstTimeBuyer }
        OPTIONAL
          { ?item  ukhpi:housePriceIndexFlatMaisonette  ?ukhpi_housePriceIndexFlatMaisonette }
        OPTIONAL
          { ?item  ukhpi:housePriceIndexFormerOwnerOccupier  ?ukhpi_housePriceIndexFormerOwnerOccupier }
        OPTIONAL
          { ?item  ukhpi:housePriceIndexMortgage  ?ukhpi_housePriceIndexMortgage }
        OPTIONAL
          { ?item  ukhpi:housePriceIndexNewBuild  ?ukhpi_housePriceIndexNewBuild }
        OPTIONAL
          { ?item  ukhpi:housePriceIndexSA  ?ukhpi_housePriceIndexSA }
        OPTIONAL
          { ?item  ukhpi:housePriceIndexSemiDetached  ?ukhpi_housePriceIndexSemiDetached }
        OPTIONAL
          { ?item  ukhpi:housePriceIndexTerraced  ?ukhpi_housePriceIndexTerraced }
        OPTIONAL
          { ?item  ukhpi:percentageAnnualChange  ?ukhpi_percentageAnnualChange }
        OPTIONAL
          { ?item  ukhpi:percentageAnnualChangeCash  ?ukhpi_percentageAnnualChangeCash }
        OPTIONAL
          { ?item  ukhpi:percentageAnnualChangeDetached  ?ukhpi_percentageAnnualChangeDetached }
        OPTIONAL
          { ?item  ukhpi:percentageAnnualChangeExistingProperty  ?ukhpi_percentageAnnualChangeExistingProperty }
        OPTIONAL
          { ?item  ukhpi:percentageAnnualChangeFirstTimeBuyer  ?ukhpi_percentageAnnualChangeFirstTimeBuyer }
        OPTIONAL
          { ?item  ukhpi:percentageAnnualChangeFlatMaisonette  ?ukhpi_percentageAnnualChangeFlatMaisonette }
        OPTIONAL
          { ?item  ukhpi:percentageAnnualChangeFormerOwnerOccupier  ?ukhpi_percentageAnnualChangeFormerOwnerOccupier }
        OPTIONAL
          { ?item  ukhpi:percentageAnnualChangeMortgage  ?ukhpi_percentageAnnualChangeMortgage }
        OPTIONAL
          { ?item  ukhpi:percentageAnnualChangeNewBuild  ?ukhpi_percentageAnnualChangeNewBuild }
        OPTIONAL
          { ?item  ukhpi:percentageAnnualChangeSemiDetached  ?ukhpi_percentageAnnualChangeSemiDetached }
        OPTIONAL
          { ?item  ukhpi:percentageAnnualChangeTerraced  ?ukhpi_percentageAnnualChangeTerraced }
        OPTIONAL
          { ?item  ukhpi:percentageChange  ?ukhpi_percentageChange }
        OPTIONAL
          { ?item  ukhpi:percentageChangeCash  ?ukhpi_percentageChangeCash }
        OPTIONAL
          { ?item  ukhpi:percentageChangeDetached  ?ukhpi_percentageChangeDetached }
        OPTIONAL
          { ?item  ukhpi:percentageChangeExistingProperty  ?ukhpi_percentageChangeExistingProperty }
        OPTIONAL
          { ?item  ukhpi:percentageChangeFirstTimeBuyer  ?ukhpi_percentageChangeFirstTimeBuyer }
        OPTIONAL
          { ?item  ukhpi:percentageChangeFlatMaisonette  ?ukhpi_percentageChangeFlatMaisonette }
        OPTIONAL
          { ?item  ukhpi:percentageChangeFormerOwnerOccupier  ?ukhpi_percentageChangeFormerOwnerOccupier }
        OPTIONAL
          { ?item  ukhpi:percentageChangeMortgage  ?ukhpi_percentageChangeMortgage }
        OPTIONAL
          { ?item  ukhpi:percentageChangeNewBuild  ?ukhpi_percentageChangeNewBuild }
        OPTIONAL
          { ?item  ukhpi:percentageChangeSemiDetached  ?ukhpi_percentageChangeSemiDetached }
        OPTIONAL
          { ?item  ukhpi:percentageChangeTerraced  ?ukhpi_percentageChangeTerraced }
        OPTIONAL
          { ?item  ukhpi:refPeriodDuration  ?ukhpi_refPeriodDuration }
        OPTIONAL
          { ?item  ukhpi:refPeriodStart  ?ukhpi_refPeriodStart }
        OPTIONAL
          { ?item  ukhpi:salesVolume  ?ukhpi_salesVolume }
        OPTIONAL
          { ?item  ukhpi:salesVolumeCash  ?ukhpi_salesVolumeCash }
        OPTIONAL
          { ?item  ukhpi:salesVolumeExistingProperty  ?ukhpi_salesVolumeExistingProperty }
        OPTIONAL
          { ?item  ukhpi:salesVolumeMortgage  ?ukhpi_salesVolumeMortgage }
        OPTIONAL
          { ?item  ukhpi:salesVolumeNewBuild  ?ukhpi_salesVolumeNewBuild }
        BIND(<http://landregistry.data.gov.uk/id/region/united-kingdom> AS ?ukhpi_refRegion)
    }

**Comment by bwmcbride** [comment]
Looks fine to me

Brian

**Comment by skwlilac** [comment]
That looks good to me too. Nice to see it worked it's way through. I'm trusting that you (@ijdickinson) are happy with the resulting query performance.
