### ISSUE TITLE
clicking too quickly on the customize your search button can result in javascript error

### ISSUE THREAD

**Issue by bwmcbride** [epimorphics/ukhpi#99]
This was seen in cucumber test ukhpi.feature scenario "change the country selection"
output:
[[
 @javascript
  Scenario: change the country selection                                    # features/ukhpi.feature:22
    Given a visitor                                                         # features/step_definitions/home_page_steps.rb:2
    When she retrieves the page "/app/ukhpi/explore"                        # features/support/web_page_steps.rb:1
    Then she should retrieve a web page                                     # features/support/web_page_steps.rb:47
    And she clicks on the change selection button                           # features/step_definitions/ukhpi-steps.rb:2
      One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).
      
      TypeError: undefined is not an object (evaluating 'this._featuresPartition[t]')
      TypeError: undefined is not an object (evaluating 'this._featuresPartition[t]')
          at http://lr-pres-staging-b.epimorphics.net/app/ukhpi/assets/application-bf4f1999c23325481a13b7944c46e9d925419932536eba0066c4dfa7ff27431f.js:18 in showLayer
          at http://lr-pres-staging-b.epimorphics.net/app/ukhpi/assets/application-bf4f1999c23325481a13b7944c46e9d925419932536eba0066c4dfa7ff27431f.js:18 in show
          at http://lr-pres-staging-b.epimorphics.net/app/ukhpi/assets/application-bf4f1999c23325481a13b7944c46e9d925419932536eba0066c4dfa7ff27431f.js:18 in onRevealPreferences
          at http://lr-pres-staging-b.epimorphics.net/app/ukhpi/assets/application-bf4f1999c23325481a13b7944c46e9d925419932536eba0066c4dfa7ff27431f.js:4 in r
          at http://lr-pres-staging-b.epimorphics.net/app/ukhpi/assets/application-bf4f1999c23325481a13b7944c46e9d925419932536eba0066c4dfa7ff27431f.js:2 in dispatch
          at http://lr-pres-staging-b.epimorphics.net/app/ukhpi/assets/application-bf4f1999c23325481a13b7944c46e9d925419932536eba0066c4dfa7ff27431f.js:2 in handle
          at http://lr-pres-staging-b.epimorphics.net/app/ukhpi/assets/application-bf4f1999c23325481a13b7944c46e9d925419932536eba0066c4dfa7ff27431f.js:2 in trigger
          at http://lr-pres-staging-b.epimorphics.net/app/ukhpi/assets/application-bf4f1999c23325481a13b7944c46e9d925419932536eba0066c4dfa7ff27431f.js:2
          at http://lr-pres-staging-b.epimorphics.net/app/ukhpi/assets/application-bf4f1999c23325481a13b7944c46e9d925419932536eba0066c4dfa7ff27431f.js:1 in each
          at http://lr-pres-staging-b.epimorphics.net/app/ukhpi/assets/application-bf4f1999c23325481a13b7944c46e9d925419932536eba0066c4dfa7ff27431f.js:1 in each
          at http://lr-pres-staging-b.epimorphics.net/app/ukhpi/assets/application-bf4f1999c23325481a13b7944c46e9d925419932536eba0066c4dfa7ff27431f.js:2 in trigger
          at http://lr-pres-staging-b.epimorphics.net/app/ukhpi/assets/application-bf4f1999c23325481a13b7944c46e9d925419932536eba0066c4dfa7ff27431f.js:19
          at http://lr-pres-staging-b.epimorphics.net/app/ukhpi/assets/application-bf4f1999c23325481a13b7944c46e9d925419932536eba0066c4dfa7ff27431f.js:4
          at :0 in sendEvent
          at phantomjs://code/web_page.js:59
          at phantomjs://code/web_page.js:558 in mouseEvent
          at phantomjs://code/node.js:67 in mouseEvent
          at phantomjs://code/browser.js:398 in mouse_event
          at phantomjs://code/browser.js:418 in click
          at phantomjs://code/browser.js:89 in runCommand
          at phantomjs://code/cmd.js:35 in run
          at phantomjs://code/main.js:17 in runCommand
          at phantomjs://code/connection.js:16 in commandReceived
          at phantomjs://code/connection.js:1 (Capybara::Poltergeist::JavascriptError)
]]
Behaviour is intermitent and more common on bwm's slow laptop than Ian's faster desktop.

**Comment by bwmcbride** [comment]
Adding a 2 second delay in the test between the "she should retrieve a web page" step and the clicking on the change selection button step, and also between that step and the "chooses Scotland" allows the test to pass successfully.

**Comment by ijdickinson** [comment]
This particular functionality will be going away as part of the redesign. It does suggest another issue though: currently, the cucumber tests are buried in the Ops Chef-recipes git repo. It would seem to make sense to separate those concerns, so that I can more easily update the integration tests as things change.

**Comment by ijdickinson** [comment]
@bwmcbride I think we can close this now as the new design doesn't have the feature that was failing in the test. Do you agree?

**Comment by bwmcbride** [comment]
yes
